"""Channel-neutral Minder operations.

Every user-facing channel (Telegram bot, future WhatsApp bot, web dashboard,
CLI) calls these operations over the ops API and renders the structured
results. Channel adapters contain ZERO business logic — they translate
between their platform and this module's result envelopes.

Routing of operations:
  - AI-routed (which camera does "the door" mean?) → SwarmKit serve topologies
  - Deterministic (device on/off, listing)         → Home Assistant REST direct
  - Replies are ALWAYS formatted here from tool-result data files, never from
    LLM prose (small local models emit unreliable final text).

Result envelope returned by every operation:
  {
    "kind": "device_action" | "device_list" | "vision" | "snapshot" | "video"
            | "setup_ha" | "setup_cameras" | "chat" | "error",
    "text": "ready-to-send reply text",
    "media": [{"type": "photo"|"video", "path": "/data/...", "caption": "..."}],
    "data": {...}   # structured details for channels that want more
  }
"""

from __future__ import annotations

import asyncio
import json
import os
import re
import shutil
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from types import ModuleType

import httpx

sys.path.insert(0, "/app/mcp-servers")
import contextlib

from _alert_sink import write_alert as _sink_write_alert
from _atomic import read_json_safe, write_json_atomic

# SwarmKit's native human-in-the-loop primitive — repairs are gated as review
# items a human resolves (via bot, dashboard, or `swarmkit review approve`).
from swarmkit_runtime.review import (
    FileReviewQueue,
    create_review_item,
)

_REPAIR_MARKER = "system-repair"  # skill_id tag identifying repair review items

DATA_DIR = Path(os.environ.get("MINDER_DATA_DIR", "/data"))
SERVE_URL = os.environ.get("SWARMKIT_URL", "http://localhost:8321")
HA_URL = os.environ.get("HA_URL", "http://localhost:8123")
FRIGATE_URL = os.environ.get("FRIGATE_URL", "http://localhost:5000").rstrip("/")
SNAPSHOT_DIR = DATA_DIR / "snapshots"
CONVERSATIONS_FILE = DATA_DIR / "ops_conversations.json"

# Recovery: precious state worth backing up (everything else is derived or
# transient — regenerated by the doctor). Backups land on a host-bind-mounted
# path so they can be copied off-box.
BACKUP_DIR = Path(os.environ.get("MINDER_BACKUP_DIR", "/backups"))
BACKUP_KEEP = int(os.environ.get("MINDER_BACKUP_KEEP", "14"))
PRECIOUS_FILES = ["rules.json", "cameras.json", "ha_token.json"]
# HA config volume (read-only mount) for full-stack DR. Restore is host-side.
HA_VOLUME_DIR = Path("/ha-config")


def _envelope(kind: str, text: str, media: list | None = None, data: dict | None = None) -> dict:
    return {"kind": kind, "text": text, "media": media or [], "data": data or {}}


# ---- Classification ----


def _has_kw(t: str, *keywords: str) -> bool:
    """Word-boundary keyword match — 'see' must not match 'seen'."""
    return any(re.search(rf"\b{re.escape(k)}\b", t) for k in keywords)


_TIME_EXPR = re.compile(
    r"\b(at\s+\d{1,2}([:.]\d{2})?\s*(am|pm)?\b"
    r"|every\s+(day|morning|afternoon|evening|night)"
    r"|daily|each\s+day)\b"
)


def classify(text: str) -> str:
    t = text.lower().strip()

    if t in ("/start", "start", "/cameras", "/setup"):
        return "setup"
    if t.startswith("/reset"):
        return "chat"
    if t.startswith("/scenario") or (
        _has_kw(t, "when", "whenever", "every time", "if")
        and _has_kw(t, "then", "turn", "switch", "alert", "notify", "send")
    ):
        return "scenario"
    # Camera listing — "list/name/what/which/how many cameras"
    if (
        _has_kw(t, "camera", "cameras")
        and _has_kw(t, "list", "name", "names", "which", "what", "all", "how many")
        and not _has_kw(t, "show", "snap", "see", "look", "photo", "picture")
    ):
        return "camera_list"
    if _has_kw(t, "devices", "smart home") or "what devices" in t:
        return "device_list"
    # Weather goes to the HA weather entity (accurate), not camera vision.
    if _has_kw(
        t,
        "weather",
        "raining",
        "rain",
        "forecast",
        "sunny",
        "cloudy",
        "overcast",
        "drizzle",
        "storm",
        "snowing",
        "humid",
        "windy",
    ):
        return "weather"
    if _has_kw(
        t,
        "turn on",
        "turn off",
        "switch on",
        "switch off",
        "lights",
        "light",
        "fan",
        "ac",
        "pump",
        "heater",
        "socket",
        "plug",
        "brightness",
        "dim",
    ):
        # "switch on the heater AT 4AM" is a schedule, not an immediate action
        if _TIME_EXPR.search(t):
            return "scenario"
        return "device"
    if t.startswith("/video") or _has_kw(t, "video", "feed", "live", "stream"):
        return "video"
    if t.startswith("/snap") or _has_kw(
        t, "show", "snap", "see", "look", "photo", "picture", "capture"
    ):
        return "snapshot"
    if (
        t.startswith("/check")
        or "?" in t
        or _has_kw(
            t,
            "is there",
            "is anyone",
            "is the",
            "are there",
            "can you see",
            "do you see",
            "how many",
            "check",
            "detect",
        )
    ):
        return "vision"
    return "chat"


# ---- Home Assistant (deterministic ops) ----


def _ha_token() -> str:
    """Get a working HA access token, refreshing if expired."""
    token_file = DATA_DIR / "ha_token.json"
    if not token_file.exists():
        return ""
    try:
        tokens = json.loads(token_file.read_text())
    except (json.JSONDecodeError, ValueError):
        return ""

    access = tokens.get("access_token", "")
    try:
        req = urllib.request.Request(
            f"{HA_URL}/api/", headers={"Authorization": f"Bearer {access}"}
        )
        urllib.request.urlopen(req, timeout=5)
        return access
    except Exception:
        pass

    try:
        refresh = tokens.get("refresh_token", "")
        form = (f"grant_type=refresh_token&refresh_token={refresh}&client_id={HA_URL}/").encode()
        req = urllib.request.Request(
            f"{HA_URL}/auth/token",
            data=form,
            headers={"Content-Type": "application/x-www-form-urlencoded"},
            method="POST",
        )
        new_tokens = json.loads(urllib.request.urlopen(req, timeout=10).read())
        write_json_atomic(
            token_file,
            {
                "access_token": new_tokens["access_token"],
                "refresh_token": refresh,
            },
        )
        return new_tokens["access_token"]
    except Exception:
        return ""


def get_ha_devices() -> list[dict]:
    token = _ha_token()
    if not token:
        return []
    try:
        req = urllib.request.Request(
            f"{HA_URL}/api/states",
            headers={"Authorization": f"Bearer {token}"},
        )
        states = json.loads(urllib.request.urlopen(req, timeout=5).read())
    except Exception:
        return []

    devices = []
    for entity in states:
        eid = entity.get("entity_id", "")
        domain = eid.split(".")[0] if "." in eid else ""
        if domain in ("light", "switch", "fan", "climate", "cover", "lock", "media_player"):
            devices.append(
                {
                    "id": eid,
                    "domain": domain,
                    "name": entity.get("attributes", {}).get("friendly_name", eid),
                    "state": entity.get("state", "unknown"),
                }
            )
    return devices


_DEVICE_STOPWORDS = {
    "can",
    "you",
    "please",
    "the",
    "a",
    "my",
    "turn",
    "switch",
    "off",
    "on",
    "toggle",
    "set",
    "is",
    "it",
    "to",
}


def control_device(text: str, device: str = "", operation: str = "") -> dict:
    """Deterministic device control — no LLM. When the router supplies the
    resolved device + operation, use them directly; otherwise parse the text."""
    devices = get_ha_devices()
    if not devices:
        return _envelope(
            "error",
            "No smart devices connected yet. Add them in the dashboard "
            "at http://minder.local (Devices tab).",
        )

    op = (operation or "").lower()
    if op in ("on", "off", "toggle"):
        action = {"on": "turn_on", "off": "turn_off", "toggle": "toggle"}[op]
    else:
        words = re.findall(r"[a-z0-9]+", text.lower())
        if "off" in words:
            action = "turn_off"
        elif "on" in words:
            action = "turn_on"
        elif "toggle" in words:
            action = "toggle"
        else:
            names = ", ".join(d["name"] for d in devices[:15])
            return _envelope("device_action", f"Tell me on or off. Devices: {names}")

    # Match against the router's device name if given, else the message words.
    query_src = device or text
    query = set(re.findall(r"[a-z0-9]+", query_src.lower())) - _DEVICE_STOPWORDS
    best, best_key = None, (0, 0)
    for d in devices:
        name_words = set(re.findall(r"[a-z0-9]+", d["name"].lower()))
        score = len(query & name_words)
        # Prefer available entities — HA keeps ghost duplicates around
        key = (score, 0 if d["state"] == "unavailable" else 1)
        if score > 0 and key > best_key:
            best, best_key = d, key

    if not best:
        names = ", ".join(d["name"] for d in devices[:15])
        return _envelope("device_action", f"Couldn't match that to a device. Available: {names}")

    token = _ha_token()
    try:
        req = urllib.request.Request(
            f"{HA_URL}/api/services/{best['domain']}/{action}",
            data=json.dumps({"entity_id": best["id"]}).encode(),
            headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
            method="POST",
        )
        urllib.request.urlopen(req, timeout=10)
        verb = {"turn_off": "turned off", "turn_on": "turned on"}.get(action, "toggled")
        return _envelope(
            "device_action",
            f"✅ {best['name']} - {verb}",
            data={"device": best["name"], "action": action, "ok": True},
        )
    except Exception as e:
        return _envelope(
            "device_action",
            f"❌ {best['name']} - failed: {e}",
            data={"device": best["name"], "action": action, "ok": False},
        )


def list_devices() -> dict:
    devices = get_ha_devices()
    if not devices:
        return _envelope(
            "device_list",
            "No smart devices connected yet. Add them at http://minder.local (Devices tab).",
        )
    lines = [f"{len(devices)} device(s):"]
    lines += [f"  • {d['name']} - {d['state']}" for d in devices]
    return _envelope("device_list", "\n".join(lines), data={"devices": devices})


def list_cameras() -> dict:
    cams = _load_cameras()
    if not cams:
        return _envelope(
            "camera_list", "No cameras discovered yet. Send /start to scan your network."
        )
    names = [c.get("name") or c["ip"] for c in cams]
    lines = [f"{len(names)} camera(s):"]
    lines += [f"  • {n}" for n in names]
    return _envelope("camera_list", "\n".join(lines), data={"cameras": names})


# ---- SwarmKit serve (AI-routed ops) ----


async def run_topology(topology: str, message: str, timeout: float = 180.0) -> str:
    async with httpx.AsyncClient(timeout=httpx.Timeout(5.0, read=timeout + 30)) as client:
        resp = await client.post(f"{SERVE_URL}/run/{topology}", json={"input": message})
        resp.raise_for_status()
        job_id = resp.json().get("job_id")
        if not job_id:
            raise RuntimeError("SwarmKit serve did not return a job_id")

        async with client.stream("GET", f"{SERVE_URL}/jobs/{job_id}/stream") as stream:
            async for line in stream.aiter_lines():
                line = line.strip()
                if line.startswith("data: ") and line[6:].startswith("[done]"):
                    break

        result = await client.get(f"{SERVE_URL}/jobs/{job_id}")
        result.raise_for_status()
        job = result.json()
        if job.get("error"):
            raise RuntimeError(job["error"])
        return job.get("output", "")


def _load_conversations() -> dict:
    if CONVERSATIONS_FILE.exists():
        try:
            return json.loads(CONVERSATIONS_FILE.read_text())
        except (json.JSONDecodeError, ValueError):
            pass
    return {}


async def send_chat(message: str, source: str) -> str:
    """Conversational fallback via minder-core, one conversation per channel.

    The conversation id is cached per channel, but serve restarts (rebuilds,
    reboots) drop the conversation — the cached id then 404s. So if a message
    POST 404s, recreate the conversation once and retry. This was the "AI runtime
    isn't reachable" error on every chat after a restart.
    """
    conversations = _load_conversations()
    conv_id = conversations.get(source)

    async with httpx.AsyncClient(timeout=httpx.Timeout(5.0, read=300.0)) as client:

        async def _new_conversation() -> str:
            resp = await client.post(f"{SERVE_URL}/conversations", json={"topology": "minder-core"})
            resp.raise_for_status()
            cid = resp.json()["id"]
            conversations[source] = cid
            CONVERSATIONS_FILE.write_text(json.dumps(conversations, indent=2))
            return cid

        if not conv_id:
            conv_id = await _new_conversation()

        for attempt in range(2):
            result_text = ""
            try:
                async with client.stream(
                    "POST",
                    f"{SERVE_URL}/conversations/{conv_id}/messages",
                    json={"message": message},
                    headers={"Accept": "text/event-stream"},
                ) as resp:
                    resp.raise_for_status()
                    async for line in resp.aiter_lines():
                        if not line.startswith("data: "):
                            continue
                        try:
                            data = json.loads(line[6:])
                            if data.get("type") == "done":
                                result_text = data.get("output", "")
                            elif data.get("type") == "error":
                                result_text = f"Error: {data.get('error', 'unknown')}"
                        except (json.JSONDecodeError, KeyError):
                            continue
                return result_text or "I couldn't generate a response."
            except httpx.HTTPStatusError as e:
                # Cached conversation vanished (serve restarted) — recreate & retry once.
                if e.response.status_code == 404 and attempt == 0:
                    conv_id = await _new_conversation()
                    continue
                raise
        return "I couldn't generate a response."


# ---- Tool-result readers (ground truth for reply formatting) ----


def _vision_checks_since(since: float) -> list[dict]:
    checks_file = DATA_DIR / "vision_checks.json"
    if not checks_file.exists():
        return []
    try:
        checks = json.loads(checks_file.read_text())
        return [c for c in checks if c.get("ts", 0) >= since]
    except (json.JSONDecodeError, ValueError):
        return []


def _extract_answer(output: str | None) -> str:
    """Pull the 'answer' field from the vision agent's structured output
    (output_schema). Falls back to the raw text if it isn't JSON."""
    if not output:
        return ""
    raw = output.strip()
    # The agent may wrap JSON in prose or fences — find the object.
    m = re.search(r"\{.*\}", raw, re.DOTALL)
    if m:
        try:
            obj = json.loads(m.group(0))
            if isinstance(obj, dict) and obj.get("answer"):
                return str(obj["answer"]).strip()
        except (json.JSONDecodeError, ValueError):
            pass
    return raw.replace("---", "").replace("***", "**").strip()


def _looks_unhelpful(text: str) -> bool:
    """Detect the garbage small models emit instead of an answer, so we can
    fall back to a deterministic reply."""
    low = text.lower()
    return (
        len(text) < 2
        or "## analysis" in low
        or "no relevant data" in low
        or low.startswith("{")
        or low.startswith("[")
        # Tool-call/instruction leakage: a confused small model echoes the
        # skill name or the function-call shape instead of an answer.
        or "check-camera-condition" in low
        or "check-condition" in low
        or "get-weather" in low
        or "get_weather" in low
        or "tool_use" in low
        or "'name':" in low
        or "'parameters'" in low
    )


_devices_tool_module = None


def _devices_module() -> ModuleType:
    """Load the devices MCP server module in-process so the backend can invoke
    its tools directly (config/setup actions, and deterministic relays where the
    3B agent loop is unreliable). The capability logic stays in the MCP server."""
    global _devices_tool_module
    if _devices_tool_module is None:
        import importlib.util

        spec = importlib.util.spec_from_file_location(
            "_minder_devices_tool", "/app/mcp-servers/tuya/server.py"
        )
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        _devices_tool_module = mod
    return _devices_tool_module


def _weather_summary() -> str:
    """Relay the get-weather MCP tool's ready-to-speak 'summary'. Authoritative
    for weather: the 3B model hallucinates a 'can't find weather' refusal in the
    agent loop instead of calling the tool, so we read the capability directly."""
    try:
        data = json.loads(_devices_module().get_weather())
        return str(data.get("summary", "")).strip()
    except Exception:
        return ""


def weather_status() -> dict:
    """Is the weather source set up, and where (for the setup UI)."""
    try:
        return json.loads(_devices_module().weather_status())
    except Exception as e:
        return {"set_up": False, "reason": str(e)}


def setup_weather(city: str = "", latitude: float = 0.0, longitude: float = 0.0) -> dict:
    """Preset weather setup (Met.no — no API key) for a city or coordinates.
    Config action, so it runs deterministically against the MCP capability."""
    try:
        return json.loads(
            _devices_module().setup_weather(city=city, latitude=latitude, longitude=longitude)
        )
    except Exception as e:
        return {"status": "error", "message": str(e), "summary": "Weather setup failed."}


def _phrase_check(question: str, check: dict) -> str:
    """Deterministic, condition-aware fallback reply when the agent's own
    text isn't usable. Phrased to what the user actually asked."""
    cam = check.get("camera", "the camera")
    match = check.get("match")
    scene = check.get("answer", "")  # YOLO counts, or the VLM's scene answer
    q = (question or "").lower()
    if any(w in q for w in ["person", "someone", "anyone", "people", "intruder", "man", "woman"]):
        subj = "person"
    elif any(w in q for w in ["car", "vehicle", "truck", "bike", "van", "bus"]):
        subj = "vehicle"
    elif any(w in q for w in ["animal", "dog", "cat", "monkey", "pet", "bird"]):
        subj = "animal"
    else:
        # Open scene question ("is the gate open", "what's in the yard"): the
        # answer is the VLM's own description — surface it, don't force the
        # person/object framing.
        if scene:
            return f"📷 {cam}: {scene.strip()}"
        return f"📷 {cam}: I couldn't get a clear read on that."
    if match:
        tail = f" (I see {scene})" if scene else ""
        return f"🔴 {cam}: yes, there's a {subj} there{tail}."
    return f"🟢 {cam}: all clear, no {subj} right now."


def collect_media_since(since: float) -> list[dict]:
    media = []
    if not SNAPSHOT_DIR.exists():
        return media
    for f in sorted(SNAPSHOT_DIR.iterdir(), key=lambda p: p.stat().st_mtime, reverse=True):
        if f.stat().st_mtime < since:
            continue
        if f.suffix == ".jpg":
            media.append({"type": "photo", "path": str(f), "caption": f.stem.replace("_", ".")})
        elif f.suffix == ".mp4":
            media.append({"type": "video", "path": str(f), "caption": f.stem.replace("_", ".")})
    photos = [m for m in media if m["type"] == "photo"][:3]
    videos = [m for m in media if m["type"] == "video"][:1]
    return photos + videos


def _load_cameras() -> list[dict]:
    cam_file = DATA_DIR / "cameras.json"
    if not cam_file.exists():
        return []
    try:
        return json.loads(cam_file.read_text())
    except (json.JSONDecodeError, ValueError):
        return []


def build_context() -> str:
    """Camera/device names injected into agent messages so the model never
    needs a list-* tool (small models loop on them)."""
    parts = []
    cameras = _load_cameras()
    if cameras:
        names = [c.get("name") or c["ip"] for c in cameras]
        parts.append(f"CAMERAS: {', '.join(names)}")
    devices = get_ha_devices()
    if devices:
        parts.append(f"DEVICES: {', '.join(d['name'] for d in devices)}")
    return "\n".join(parts)


# ---- Scenarios (natural language → structured rule) ----
#
# A SwarmKit agent (minder-scenario topology) understands the request and
# calls the create_monitoring_rule MCP tool once with flat parameters. The
# tool validates and writes the rule; we format the reply from the rule it
# wrote — never from the agent's prose.


RULES_FILE = DATA_DIR / "rules.json"


def _rules_created_since(since: float) -> list[dict]:
    if not RULES_FILE.exists():
        return []
    try:
        rules = json.loads(RULES_FILE.read_text())
        return [r for r in rules if r.get("created_ts", 0) >= since]
    except (json.JSONDecodeError, ValueError):
        return []


# The minder-scenario topology is a single worker agent whose output_schema
# carries the rule fields. Schema-constrained decoding (SwarmKit >= 1.3.5)
# makes even the 3B local model emit on-schema JSON, so the agent extracts and
# this module validates the field values and persists the rule — the agent
# never writes anything.


def _normalize_time(s: str) -> str:
    s = (s or "").strip().lower().replace(".", ":")
    m = re.fullmatch(r"(\d{1,2})(?::(\d{2}))?\s*(am|pm)?", s)
    if not m:
        return ""
    h, minute = int(m[1]), int(m[2] or 0)
    if m[3] == "pm" and h != 12:
        h += 12
    if m[3] == "am" and h == 12:
        h = 0
    if not (0 <= h < 24 and 0 <= minute < 60):
        return ""
    return f"{h:02d}:{minute:02d}"


def _match_camera_name(requested: str) -> str:
    requested = (requested or "").lower().strip()
    if requested in ("", "all", "any", "all cameras"):
        return "all"
    req_words = set(re.findall(r"[a-z0-9]+", requested))
    best, best_score = "all", 0
    for c in _load_cameras():
        name = c.get("name") or c["ip"]
        words = set(re.findall(r"[a-z0-9]+", name.lower()))
        score = len(req_words & words)
        if score > best_score:
            best, best_score = name, score
    return best


def _match_device_name(requested: str) -> str | None:
    req_words = set(re.findall(r"[a-z0-9]+", (requested or "").lower())) - _DEVICE_STOPWORDS
    best, best_key = None, (0, 0)
    for d in get_ha_devices():
        words = set(re.findall(r"[a-z0-9]+", d["name"].lower()))
        score = len(req_words & words)
        key = (score, 0 if d["state"] == "unavailable" else 1)
        if score > 0 and key > best_key:
            best, best_key = d["name"], key
    return best


async def create_scenario(text: str) -> dict:
    """Create a rule from natural language via the minder-scenario worker
    agent. The agent extracts on-schema fields (output_schema-constrained);
    this module validates the values and persists the rule. The reply is
    always formatted from the rule that was actually persisted."""
    clean = re.sub(r"^/scenario\s*", "", text.strip(), flags=re.I)

    context = build_context()
    enriched = f"{context}\n\n{clean}" if context else clean
    try:
        output = await asyncio.wait_for(run_topology("minder-scenario", enriched), timeout=120)
        parsed = _extract_json(output)
    except Exception as e:
        return _envelope("error", f"Scenario creation failed: {e}")
    if not parsed:
        return _envelope(
            "error",
            "I couldn't understand that scenario. Try: "
            '"when someone is outside after 10pm, turn on the porch light"',
        )

    return _persist_scenario(parsed, clean)


def _extract_json(output: str) -> dict | None:
    """Parse the worker's structured output. With output_schema the agent
    returns raw JSON, but tolerate stray text around it just in case."""
    output = (output or "").strip()
    if not output:
        return None
    try:
        obj = json.loads(output)
        return obj if isinstance(obj, dict) else None
    except (json.JSONDecodeError, ValueError):
        pass
    start, end = output.find("{"), output.rfind("}")
    if 0 <= start < end:
        try:
            obj = json.loads(output[start : end + 1])
            return obj if isinstance(obj, dict) else None
        except (json.JSONDecodeError, ValueError):
            return None
    return None


def _device_grounded_in_request(device: str, request: str) -> bool:
    """A required string field forces the small model to emit *a* device even
    for alert-only requests. Keep the device only if the user's words actually
    overlap the matched device name — otherwise it was hallucinated."""
    dev_words = set(re.findall(r"[a-z0-9]+", (device or "").lower())) - _DEVICE_STOPWORDS
    req_words = set(re.findall(r"[a-z0-9]+", (request or "").lower()))
    return bool(dev_words & req_words)


def _rule_cameras(rule: dict) -> list[str]:
    """Cameras a rule watches, as a list. Backward-compatible with rules that
    stored a single ``camera`` string before multi-camera support."""
    cams = rule.get("cameras")
    if isinstance(cams, list) and cams:
        return cams
    return [rule.get("camera", "all")]


def _coerce_str_list(value: object, single_key_value: object = None) -> list[str]:
    """Normalize a worker field to a list of non-empty strings, tolerating the
    old single-string field (``single_key_value``) and stray scalars."""
    if isinstance(value, list):
        items = value
    elif value is None:
        items = [single_key_value] if single_key_value else []
    else:
        items = [value]
    return [str(x).strip() for x in items if str(x).strip()]


def _schedule_to_ha_condition(schedule: str) -> list[dict]:
    """Map a rule schedule to an HA time condition (for motion reflexes). HA
    handles after>before as a window that wraps midnight."""
    s = (schedule or "always").strip()
    if s in ("", "always"):
        return []
    if s == "night":
        return [{"condition": "time", "after": "20:00:00", "before": "06:00:00"}]
    if s == "day":
        return [{"condition": "time", "after": "06:00:00", "before": "20:00:00"}]
    m = re.fullmatch(r"(\d{1,2}):(\d{2})-(\d{1,2}):(\d{2})", s)
    if m:
        return [
            {
                "condition": "time",
                "after": f"{int(m[1]):02d}:{m[2]}:00",
                "before": f"{int(m[3]):02d}:{m[4]}:00",
            }
        ]
    return []


def _camera_motion_entities(cameras: list[str]) -> list[str] | None:
    """Resolve a rule's cameras to their HA motion sensors — but only if EVERY
    camera is HA-tier. Returns None otherwise (Frigate detection isn't an HA
    entity, so HA can't trigger on it; those stay Minder-managed)."""
    if not cameras or "all" in cameras:
        return None
    inv = {(c.get("name") or "").lower(): c for c in _load_cameras()}
    ents = []
    for name in cameras:
        c = inv.get((name or "").lower())
        if not c or c.get("tier") != "ha-snapshot" or not c.get("ha_entity"):
            return None
        ents.append(c["ha_entity"])
    return ents or None


def _ha_device_services(device_actions: list[dict]) -> list[dict]:
    by_name = {d["name"].lower(): d for d in get_ha_devices()}
    out = []
    for act in device_actions:
        d = by_name.get((act.get("device") or "").lower())
        if d:
            out.append(
                {"service": f"{d['domain']}.{act['action']}", "target": {"entity_id": d["id"]}}
            )
    return out


def _deploy_automation(
    automation_id: str,
    triggers: list[dict],
    conditions: list[dict],
    device_actions: list[dict],
    label: str,
) -> str:
    """Deploy a native HA automation (trigger → device service calls) via HA's
    config API. Returns the automation id on success, '' otherwise."""
    token = _ha_token()
    if not token:
        return ""
    ha_actions = _ha_device_services(device_actions)
    if not ha_actions:
        return ""
    config = {
        "alias": f"Minder: {label}",
        "trigger": triggers,
        "condition": conditions,
        "action": ha_actions,
        "mode": "single",
    }
    try:
        for path, body in (
            (f"/api/config/automation/config/{automation_id}", config),
            ("/api/services/automation/reload", {}),
        ):
            req = urllib.request.Request(
                f"{HA_URL}{path}",
                data=json.dumps(body).encode(),
                headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
                method="POST",
            )
            urllib.request.urlopen(req, timeout=10)
        return automation_id
    except Exception:
        return ""


def _compile_ha_reflex(rule: dict) -> str:
    """If the scenario is a pure HA reflex — device-only (no alert) on either a
    daily time trigger OR motion from HA-tier cameras — deploy it as a native
    HA automation and return its id. Else '' (stays Minder-managed). Native HA
    automations are exact, instant, and survive Minder being down."""
    actions = rule.get("actions", [])
    device_actions = [a for a in actions if a.get("type") == "device"]
    if not device_actions or any(a.get("type") == "alert" for a in actions):
        return ""
    aid = f"minder_{int(rule['created_ts'])}"
    at_time, condition = rule.get("at_time"), rule.get("condition")
    if at_time and not condition:
        return _deploy_automation(
            aid,
            [{"platform": "time", "at": f"{at_time}:00"}],
            [],
            device_actions,
            f"every day at {at_time}",
        )
    if condition and not at_time:
        motion = _camera_motion_entities(rule.get("cameras", []))
        if motion:
            return _deploy_automation(
                aid,
                [{"platform": "state", "entity_id": motion, "to": "on"}],
                _schedule_to_ha_condition(rule.get("schedule", "always")),
                device_actions,
                f"{condition} → device",
            )
    return ""


def _plan_to_rule(plan: dict) -> tuple[dict, str]:
    """Map the router's scenario plan to the fields _persist_scenario expects.
    The router already parsed the trigger/device/schedule, so this is a pure
    translation — no LLM. Returns (parsed, trigger_type)."""
    tt = (plan.get("trigger_type") or "").lower()
    op = (plan.get("operation") or "").lower()
    device = (plan.get("device") or "").strip()
    parsed: dict = {
        "cameras": [],
        "condition": "",
        "schedule": (plan.get("schedule") or "always").strip() or "always",
        "at_time": "",
        "devices": [device] if device else [],
        "device_action": {"on": "turn_on", "off": "turn_off"}.get(op, ""),
        "alert": True,
    }
    if tt == "vision":
        obj = (plan.get("trigger_object") or "person").strip().lower()
        parsed["condition"] = f"is there a {obj}"
        parsed["cameras"] = [plan.get("trigger_camera") or "all"]
    elif tt == "time":
        parsed["at_time"] = plan.get("at") or ""
    return parsed, tt


async def author_scenario(plan: dict, text: str) -> dict:
    """Deterministic scenario authoring from the router's plan — no second agent.
    Sensor triggers aren't supported by the rule engine yet (vision + time only)."""
    parsed, tt = _plan_to_rule(plan)
    if tt == "sensor":
        return _envelope(
            "scenario",
            "Sensor-based rules (like 'when the water level is reached') aren't "
            "supported yet — I can trigger on what a camera sees or at a set time.",
        )
    return await asyncio.to_thread(_persist_scenario, parsed, text)


def _persist_scenario(parsed: dict, request: str = "") -> dict:
    """Validate the worker's extracted fields and write the rule. Supports
    multiple cameras and multiple devices, and compiles pure time→device
    reflexes to native HA automations (Phase 5)."""
    at_time = _normalize_time(parsed.get("at_time", ""))
    condition = (parsed.get("condition") or "").strip()
    if not condition and not at_time:
        return _envelope(
            "error",
            "I couldn't understand that scenario. Try: "
            '"when someone is outside after 10pm, turn on the porch light"',
        )

    # Cameras: match each requested name; "all" collapses the whole rule to all.
    requested_cams = _coerce_str_list(parsed.get("cameras"), parsed.get("camera"))
    if not requested_cams:
        requested_cams = ["all"]
    cameras: list[str] = []
    for c in requested_cams:
        m = _match_camera_name(c)
        if m == "all":
            cameras = ["all"]
            break
        if m not in cameras:
            cameras.append(m)
    if not cameras:
        cameras = ["all"]

    schedule = (parsed.get("schedule") or "always").strip()
    if not re.fullmatch(r"always|night|day|\d{1,2}:\d{2}-\d{1,2}:\d{2}", schedule):
        schedule = "always"

    # Devices: one action applied to every grounded, matched device.
    requested_devs = _coerce_str_list(parsed.get("devices"), parsed.get("device"))
    action = parsed.get("device_action")
    actions: list[dict] = []
    warnings: list[str] = []
    if action in ("turn_on", "turn_off"):
        seen: set[str] = set()
        for d in requested_devs:
            if not _device_grounded_in_request(d, request):
                continue
            matched = _match_device_name(d)
            if matched and matched not in seen:
                seen.add(matched)
                actions.append({"type": "device", "device": matched, "action": action})
            elif not matched:
                warnings.append(f"no device matched '{d}'")
    if parsed.get("alert", True) or not actions:
        actions.insert(0, {"type": "alert"})

    created_ts = time.time()
    rule = {
        "cameras": cameras,
        "condition": condition,
        "schedule": schedule,
        "enabled": True,
        "actions": actions,
        "at_time": at_time,
        "created_ts": created_ts,
        "target": "minder",
    }

    # Phase 5 — compile pure device reflexes (time→device, or motion→device on
    # HA-tier cameras) to a native HA automation. Tagged target="ha" so the
    # Minder poller skips it (no double-fire); it still lives in rules.json so
    # the rule list stays complete.
    aid = _compile_ha_reflex(rule)
    if aid:
        rule["target"] = "ha"
        rule["ha_automation_id"] = aid

    rules = []
    if RULES_FILE.exists():
        with contextlib.suppress(json.JSONDecodeError, ValueError):
            rules = json.loads(RULES_FILE.read_text())
    for existing in rules:
        if (
            sorted(_rule_cameras(existing)) == sorted(cameras)
            and existing.get("condition") == rule["condition"]
            and existing.get("schedule") == rule["schedule"]
            and existing.get("at_time", "") == rule["at_time"]
        ):
            return _envelope(
                "scenario", "That scenario already exists.", data={"rules": [existing]}
            )
    rules.append(rule)
    write_json_atomic(RULES_FILE, rules)

    created = [rule]
    if warnings:
        created[0]["_warnings"] = warnings
    return _format_scenario_reply(created)


def _format_scenario_reply(created: list[dict]) -> dict:
    parts = []
    for rule in created:
        cams = _rule_cameras(rule)
        cam_label = "all cameras" if cams == ["all"] else ", ".join(cams)
        if rule.get("at_time"):
            where = " (runs locally in Home Assistant)" if rule.get("target") == "ha" else ""
            parts.append(f"Scenario created - every day at {rule['at_time']}{where}:")
        else:
            parts.append(
                f'Scenario created - when "{rule["condition"]}" on '
                f"{cam_label} ({rule.get('schedule', 'always')}):"
            )
        for a in rule.get("actions", []):
            if a["type"] == "alert":
                parts.append("  • send an alert")
            else:
                parts.append(f"  • {a['action'].replace('_', ' ')} {a['device']}")
        for w in rule.get("_warnings", []):
            parts.append(f"  ⚠ {w}")
    return _envelope("scenario", "\n".join(parts), data={"rules": created})


# ---- Recovery (backup / restore / doctor / health) ----
#
# State is spread across volumes; writes are atomic (prevent corruption) and a
# small set of PRECIOUS files are backed up so they can be restored. Everything
# else is derived (Frigate config ← cameras.json) or transient, so the doctor
# regenerates rather than restores it.


def _file_status(path: Path) -> str:
    if not path.exists():
        return "missing"
    try:
        data = json.loads(path.read_text())
    except (json.JSONDecodeError, ValueError):
        return "corrupt"
    return "empty" if data in ([], {}, None) else "ok"


def backup() -> dict:
    """Snapshot the parseable precious files to a timestamped backup dir and
    rotate. Never backs up a corrupt file (would poison a restore)."""
    ts = time.strftime("%Y%m%d-%H%M%S", time.localtime())
    dest = BACKUP_DIR / ts
    dest.mkdir(parents=True, exist_ok=True)
    saved = []
    for name in PRECIOUS_FILES:
        src = DATA_DIR / name
        if src.exists() and _file_status(src) in ("ok", "empty"):
            (dest / name).write_text(src.read_text())
            saved.append(name)
    dirs = sorted([p for p in BACKUP_DIR.iterdir() if p.is_dir()])
    for old in dirs[:-BACKUP_KEEP]:
        shutil.rmtree(old, ignore_errors=True)
    return {"ts": ts, "files": saved, "path": str(dest)}


def list_backups() -> list[dict]:
    if not BACKUP_DIR.exists():
        return []
    return [
        {"ts": p.name, "files": sorted(f.name for f in p.iterdir())}
        for p in sorted((d for d in BACKUP_DIR.iterdir() if d.is_dir()), reverse=True)
    ]


def _ha_tar_filter(tarinfo):
    """Skip the recorder DB, logs, and TTS cache — huge and disposable. Keep
    .storage (auth/entities/integrations), automations, custom_components."""
    base = tarinfo.name.rsplit("/", 1)[-1]
    if (
        base.startswith("home-assistant_v2.db")
        or base.endswith((".log", ".log.1"))
        or "/tts/" in tarinfo.name
        or "/deps/" in tarinfo.name
    ):
        return None
    return tarinfo


def backup_ha_volume() -> dict:
    """Tar the HA config volume (config-only, no recorder DB) to the host
    backups path for full-stack disaster recovery. Live snapshot — HA writes
    .storage atomically per-file, so this is consistent enough for DR."""
    import tarfile

    if not HA_VOLUME_DIR.exists():
        return {"status": "skipped", "reason": "ha-config not mounted"}
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    ts = time.strftime("%Y%m%d-%H%M%S", time.localtime())
    out = BACKUP_DIR / f"ha-config-{ts}.tar.gz"
    tmp = out.with_suffix(".tmp")
    try:
        with tarfile.open(tmp, "w:gz") as tf:
            tf.add(HA_VOLUME_DIR, arcname=".", filter=_ha_tar_filter)
        os.replace(tmp, out)
    except Exception as e:
        return {"status": "error", "message": str(e)[:200]}
    for old in sorted(BACKUP_DIR.glob("ha-config-*.tar.gz"))[:-BACKUP_KEEP]:
        old.unlink(missing_ok=True)
    return {"status": "ok", "file": out.name, "size_kb": out.stat().st_size // 1024}


def _latest_good_backup(filename: str) -> Path | None:
    if not BACKUP_DIR.exists():
        return None
    for d in sorted((d for d in BACKUP_DIR.iterdir() if d.is_dir()), reverse=True):
        cand = d / filename
        if cand.exists() and _file_status(cand) in ("ok", "empty"):
            return cand
    return None


def _is_problem(name: str, status: str) -> bool:
    """A precious file is a genuine fault only if it's corrupt (restore from
    backup), or missing AND a good backup exists (it was there before → real
    loss). Missing with no backup is just not-set-up-yet (fresh install / no
    scenarios) — not a fault, so it never raises an alert."""
    if status == "corrupt":
        return True
    if status == "missing":
        return _latest_good_backup(name) is not None
    return False


def restore(ts: str = "") -> dict:
    """Restore precious files from a backup (a specific ts, or the latest good
    copy of each file if ts is empty)."""
    restored = []
    for name in PRECIOUS_FILES:
        src = (BACKUP_DIR / ts / name) if ts else _latest_good_backup(name)
        if src and src.exists() and _file_status(src) in ("ok", "empty"):
            write_json_atomic(DATA_DIR / name, json.loads(src.read_text()))
            restored.append(name)
    return {"restored": restored, "ts": ts or "latest"}


def health() -> dict:
    files = {name: _file_status(DATA_DIR / name) for name in PRECIOUS_FILES}
    frigate_ok = False
    try:
        urllib.request.urlopen(f"{FRIGATE_URL}/api/version", timeout=5)
        frigate_ok = True
    except Exception:
        pass
    backups = list_backups()
    ha_tars = sorted(BACKUP_DIR.glob("ha-config-*.tar.gz")) if BACKUP_DIR.exists() else []
    return {
        "files": files,
        "ha": bool(_ha_token()),
        "frigate": frigate_ok,
        "backups": len(backups),
        "latest_backup": backups[0]["ts"] if backups else None,
        "ha_volume_backups": len(ha_tars),
        "latest_ha_volume_backup": ha_tars[-1].name if ha_tars else None,
        # Healthy unless a file is a genuine fault. Missing-on-fresh-install
        # (no backup yet) is "not set up", not unhealthy.
        "healthy": not any(_is_problem(n, s) for n, s in files.items()),
    }


def _review_queue() -> FileReviewQueue:
    return FileReviewQueue(DATA_DIR)


def _pending_repairs() -> list:
    return [it for it in _review_queue().list_pending() if it.skill_id == _REPAIR_MARKER]


def diagnose_and_alert() -> dict:
    """Detect problems and, if unhealthy, file a repair as a SwarmKit review
    item (the native HITL gate) and alert the human to approve it. NEVER fixes
    anything — the fix runs only when the review item is resolved 'approved'."""
    h = health()
    # Only file a repair the doctor can actually apply (restore corrupt/lost
    # files). HA/Frigate being unreachable isn't doctor-repairable — it's shown
    # in health() but never raises a repair-approval alert.
    bad = [f"{f} ({s})" for f, s in h["files"].items() if _is_problem(f, s)]
    if bad:
        if not _pending_repairs():
            item = create_review_item(
                topology_id="minder-doctor",
                agent_id="doctor",
                skill_id=_REPAIR_MARKER,
                output="Restore corrupt/missing state from the last good backup "
                "and regenerate derived config.",
                verdict="needs-revision",
                reason="Health issue: " + "; ".join(bad),
            )
            _review_queue().submit(item)
            short = item.id[:8]
            _sink_write_alert(
                "Minder found a problem and needs your approval to fix it: "
                + "; ".join(bad)
                + f".\nApprove: /approve {short}   Dismiss: /reject {short}",
                "",
            )
            h["review_id"] = item.id
        else:
            pending = _pending_repairs()[0]
            h["review_id"] = pending.id
            # Re-remind while still pending (the 6h doctor cron drives this);
            # 5h cooldown so restart storms don't spam.
            st = read_json_safe(DATA_DIR / "monitor_state.json", {}) or {}
            if time.time() - st.get("_health_reminder_ts", 0) > 5 * 3600:
                _sink_write_alert(
                    "Reminder: a repair still needs your approval — "
                    f"/approve {pending.id[:8]} (or open the dashboard).",
                    "",
                )
                st["_health_reminder_ts"] = time.time()
                write_json_atomic(DATA_DIR / "monitor_state.json", st)
    return h


def list_approvals() -> list[dict]:
    """Pending repair approvals (SwarmKit review items awaiting a human)."""
    return [
        {
            "id": it.id,
            "short": it.id[:8],
            "reason": it.reason,
            "action": it.output,
            "ts": it.timestamp,
        }
        for it in _pending_repairs()
    ]


async def approve_repair(item_id: str = "") -> dict:
    """Human approval: resolve the review item 'approved' and THEN run the
    repair. This is the only path that applies a fix."""
    pending = _pending_repairs()
    if not pending:
        return {"status": "none", "message": "No repair is awaiting approval."}
    item = (
        next((it for it in pending if it.id.startswith(item_id)), pending[0])
        if item_id
        else pending[0]
    )
    _review_queue().resolve(item.id, "approved")
    report = await doctor(repair=True)  # gated action — runs only after approval
    return {
        "status": "approved",
        "item_id": item.id,
        "repaired": report.get("repaired", []),
        "regenerated": report.get("regenerated", []),
    }


def reject_repair(item_id: str = "") -> dict:
    """Human dismissal: resolve the review item 'rejected'; no fix runs."""
    pending = _pending_repairs()
    if not pending:
        return {"status": "none"}
    item = (
        next((it for it in pending if it.id.startswith(item_id)), pending[0])
        if item_id
        else pending[0]
    )
    _review_queue().resolve(item.id, "rejected")
    return {"status": "rejected", "item_id": item.id}


async def doctor(repair: bool = False) -> dict:
    """Validate state; when repair=True, restore corrupt/missing precious files
    from the latest good backup and regenerate derived state (Frigate config
    from cameras.json)."""
    report: dict = {"checked": {}, "repaired": [], "regenerated": []}
    for name in PRECIOUS_FILES:
        st = _file_status(DATA_DIR / name)
        report["checked"][name] = st
        if repair and st in ("missing", "corrupt"):
            good = _latest_good_backup(name)
            if good:
                write_json_atomic(DATA_DIR / name, json.loads(good.read_text()))
                report["repaired"].append(name)
    if repair and _file_status(DATA_DIR / "cameras.json") == "ok":
        try:
            await run_topology("minder-frigate-config", "Configure Frigate", timeout=120)
            report["regenerated"].append("frigate-config")
        except Exception:
            pass
    return report


# ---- Operations ----


async def setup_ha() -> dict:
    try:
        await run_topology("minder-ha-setup", "Set up Home Assistant", timeout=60)
        return _envelope("setup_ha", "Smart home backend ready.")
    except Exception as e:
        return _envelope("setup_ha", f"Smart home setup skipped ({e}).")


async def setup_cameras(subnet: str = "") -> dict:
    started = time.time()
    message = f"Discover cameras on subnet {subnet}" if subnet else "Discover cameras"
    try:
        await run_topology("minder-discover", message, timeout=180)
    except TimeoutError:
        return _envelope("setup_cameras", "Camera discovery timed out. Try again.")
    except Exception as e:
        return _envelope("setup_cameras", f"Camera discovery failed: {e}")

    cameras = _load_cameras()
    if cameras:
        # Push the discovered RTSP cameras into Frigate (generates its config
        # from the inventory). Best-effort — never block discovery on it.
        with contextlib.suppress(Exception):
            await run_topology("minder-frigate-config", "Configure Frigate", timeout=120)
        lines = [f"Found {len(cameras)} camera(s):"]
        lines += [f"  {i}. {c.get('name') or c['ip']}" for i, c in enumerate(cameras, 1)]
        lines.append("\nTry: /snap porch, /check is anyone at the gate, /video main door")
        text = "\n".join(lines)
    else:
        text = (
            "No cameras found. Check that cameras are powered on, "
            "or configure the subnet at http://minder.local"
        )

    return _envelope(
        "setup_cameras", text, media=collect_media_since(started), data={"cameras": cameras}
    )


def pending_alerts() -> list[dict]:
    """Read and clear pending monitoring alerts (channel adapters poll this)."""
    alert_file = DATA_DIR / "pending_alerts.json"
    if not alert_file.exists():
        return []
    try:
        alerts = json.loads(alert_file.read_text())
    except (json.JSONDecodeError, ValueError):
        return []
    if alerts:
        alert_file.write_text("[]")
    return alerts


def _cameras_configured() -> bool:
    return len(_load_cameras()) > 0


OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434").rstrip("/")
VISION_MODEL = os.environ.get("MINDER_VISION_MODEL", "llava-phi3")
# Routing is the minder-router topology (output_schema Plan) via route(); the
# old route-tool / constrained-generation classifier was removed — the keyword
# classify() is the only fallback now.


# Router intent -> the dispatch kind handle_message already understands.
_ROUTER_KIND = {
    "query": "vision",
    "snapshot": "snapshot",
    "video": "video",
    "device_now": "device",
    "scenario": "scenario",
    "weather": "weather",
    "camera_list": "camera_list",
    "device_list": "device_list",
    "setup": "setup",
    "chat": "chat",
}


async def route(text: str) -> dict | None:
    """Run the minder-router topology and parse its structured Plan. The router
    (output_schema, no tools) understands the message and emits the whole plan in
    one call; this is the PRIMARY path. Returns the plan dict with a mapped
    'dispatch_kind', or None if the router is unavailable (serve down) — the
    caller then falls back to the keyword classifier."""
    try:
        ctx = build_context()
        enriched = f"{ctx}\n\n{text}" if ctx else text
        out = await asyncio.wait_for(run_topology("minder-router", enriched), timeout=150)
    except Exception:
        return None
    plan = _extract_json(out)
    if not isinstance(plan, dict) or not plan.get("kind"):
        return None
    _correct_plan(plan, text)
    plan["dispatch_kind"] = _ROUTER_KIND.get(plan["kind"], "chat")
    return plan


def _correct_plan(plan: dict, text: str) -> None:
    """Deterministic guard on the router's intent. A scenario is, by definition,
    a standing rule with a future TRIGGER (when/if/every/at-a-time). So a plain
    question with no such trigger can never be a scenario — force it to query.
    Keys on sentence structure, not keywords the 3B can wobble on. Mutates plan."""
    t = text.strip().lower()
    if plan.get("kind") != "scenario":
        return
    has_trigger = bool(re.search(r"\b(when|whenever|if|every|each|after|before)\b", t)) or bool(
        _TIME_EXPR.search(t)
    )
    is_question = t.endswith("?") or bool(
        re.match(r"(is|are|was|were|who|what|which|where|do|does|did|can|how|any)\b", t)
    )
    if is_question and not has_trigger:
        plan["kind"] = "query"


def _resolve_cameras(plan: dict) -> list[str]:
    """Resolve the router's camera list to concrete configured names — zone-aware.
    Expands ["all"]/"outside"/"inside" against cameras.json (zone defaults to
    'outdoor' for security cams), validates names, drops unknowns. The tag is
    authoritative; the model's list is a hint we re-resolve."""
    cams = _load_cameras()
    names = [c.get("name") or c["ip"] for c in cams]
    req = plan.get("cameras") or []
    if not req or any(str(x).strip().lower() in ("all", "any", "") for x in req):
        return names
    out: list[str] = []
    for x in req:
        xl = str(x).strip().lower()
        if xl in ("outside", "outdoor"):
            out += [c.get("name") or c["ip"] for c in cams if c.get("zone", "outdoor") == "outdoor"]
        elif xl in ("inside", "indoor"):
            out += [c.get("name") or c["ip"] for c in cams if c.get("zone", "outdoor") == "indoor"]
        else:
            m = _match_camera_name(str(x))
            if m and m != "all":
                out.append(m)
            elif x in names:
                out.append(str(x))
    seen: set[str] = set()
    deduped = [c for c in out if not (c in seen or seen.add(c))]
    return deduped or names


# ---- Deterministic vision execution ----
# The router already parsed camera + subject; the backend runs YOLO/VLM directly.
# No agent: small models can't reliably orchestrate the tool call (proven), but
# YOLO and a single VLM call are deterministic code.

_detector_mod: ModuleType | None = None


def _yolo() -> ModuleType:
    """Lazy-import the shared YOLO detector (model itself loads on first detect)."""
    global _detector_mod
    if _detector_mod is None:
        sys.path.insert(0, "/app/mcp-servers/detect")
        import detector as d

        _detector_mod = d
    return _detector_mod


def _subject_classes(subject: str) -> set | None:
    d = _yolo()
    return {
        "person": d.PERSON_CLASSES,
        "vehicle": d.VEHICLE_CLASSES,
        "animal": d.ANIMAL_CLASSES,
    }.get(subject)


def _grab_frame(camera: str) -> Path | None:
    """Fetch the camera's current frame deterministically and save it to the
    snapshot dir (so collect_media_since picks it up). Frigate tier → latest.jpg."""
    cam = next(
        (
            c
            for c in _load_cameras()
            if (c.get("name") or "").lower() == camera.lower() or c.get("ip") == camera
        ),
        None,
    )
    if not cam:
        return None
    name = cam.get("name") or cam["ip"]
    slug = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
    dest = SNAPSHOT_DIR / f"{cam['ip'].replace('.', '_')}.jpg"
    try:
        data = urllib.request.urlopen(f"{FRIGATE_URL}/api/{slug}/latest.jpg", timeout=8).read()
        if data[:2] == b"\xff\xd8":
            SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(data)
            return dest
    except Exception:
        pass
    return None


def _grab_frames(cams: list[str]) -> list[Path]:
    """Grab a current frame for each camera (for snapshot replies)."""
    return [f for f in (_grab_frame(c) for c in cams) if f]


def _vlm_answer(frame_b64: str, question: str, camera: str = "") -> str:
    """One direct VLM (llava-phi3, CPU) call for an open-scene question. Pass the
    user's ACTUAL words (not the router's condition rewrite — it mangles "describe
    the scene" into a yes/no), and instruct the model to answer or describe."""
    where = f" of the {camera}" if camera else ""
    q = (question or "").strip() or "What do you see?"
    _content = (
        f"You are a home security camera assistant. Look at this camera image{where}. "
        f'The user asked: "{q}". Answer their question in one short, factual sentence '
        "based only on what you see. If they asked you to describe the scene or what's "
        "there, describe what you see (people, vehicles, anything notable)."
    )
    payload = json.dumps(
        {
            "model": VISION_MODEL,
            "messages": [
                {
                    "role": "user",
                    "content": _content,
                    "images": [frame_b64],
                }
            ],
            "stream": False,
            "think": False,
            "keep_alive": -1,
            "options": {"temperature": 0.1, "num_predict": 120, "num_gpu": 0},
        }
    ).encode()
    try:
        req = urllib.request.Request(
            f"{OLLAMA_URL}/api/chat", data=payload, headers={"Content-Type": "application/json"}
        )
        r = json.loads(urllib.request.urlopen(req, timeout=200).read())
        return (r.get("message", {}).get("content") or "").strip()
    except Exception:
        return ""


def _run_vision_checks(
    cams: list[str], subject: str, question: str, open_scene: bool
) -> list[dict]:
    """Per camera: grab a frame, then YOLO (objects) or the VLM (open scene).
    Synchronous — call via asyncio.to_thread."""
    import base64

    d = _yolo()
    results: list[dict] = []
    for cam in cams:
        frame = _grab_frame(cam)
        if not frame:
            results.append({"camera": cam, "error": "no frame"})
            continue
        if open_scene:
            ans = _vlm_answer(base64.b64encode(frame.read_bytes()).decode(), question, cam)
            results.append({"camera": cam, "open": True, "answer": ans})
        else:
            want = _subject_classes(subject) or d.classes_for_condition(question or subject)
            res = d.detect(str(frame), want_classes=want)
            results.append(
                {
                    "camera": cam,
                    "match": res["matched"] > 0,
                    "count": res["matched"],
                    "scene": d.describe_counts(res["counts"]),
                }
            )
    return results


async def _dispatch_query(plan: dict, started: float, text: str = "") -> dict:
    """Deterministic vision query: YOLO for person/vehicle/animal, VLM for open
    scene questions, on the camera(s) the router resolved. No agent.

    For open-scene the VLM gets the user's ORIGINAL text, not the router's
    `condition` (which the 3B mangles — e.g. "describe the scene" became "is there
    anyone?", and the VLM answered "No")."""
    cams = _resolve_cameras(plan)
    if not cams:
        return _envelope("vision", "No cameras are configured yet. Send /start to set them up.")
    subject = (plan.get("subject") or "").lower()
    question = text or plan.get("condition") or ""
    open_scene = subject == "open" or (
        subject not in ("person", "vehicle", "animal") and _subject_classes(subject) is None
    )
    results = await asyncio.to_thread(_run_vision_checks, cams, subject, question, open_scene)
    media = collect_media_since(started)

    if open_scene:
        r = next((x for x in results if x.get("answer")), None)
        cam = (r or results[0]).get("camera", "the camera")
        ans = (r or {}).get("answer")
        text = f"📷 {cam}: {ans}" if ans else f"📷 {cam}: I couldn't get a clear read on that."
        return _envelope("vision", text, media=media)

    subj = subject if subject in ("person", "vehicle", "animal") else "person"
    checked = [r for r in results if "match" in r]
    if not checked:
        return _envelope("vision", "I couldn't capture from that camera right now.", media=media)
    hits = [r for r in checked if r["match"]]
    if hits:
        where = ", ".join(r["camera"] for r in hits)
        return _envelope("vision", f"🔴 Yes — {subj} at {where}.", media=media)
    spot = checked[0]["camera"] if len(checked) == 1 else f"{len(checked)} cameras"
    return _envelope("vision", f"🟢 All clear — no {subj} on {spot} right now.", media=media)


async def handle_message(
    text: str, source: str = "default", sender: str = "", kind: str | None = None
) -> dict:
    """THE channel-neutral entry point. Classify, execute, return envelope.

    Routing is router-primary: the minder-router agent understands the message
    and emits a structured plan in one call; we dispatch on its intent. The
    keyword classifier is only the fallback for when the router is unavailable
    (serve down). The plan's extracted entities (cameras, etc.) feed the
    deterministic execution below.
    """
    plan: dict | None = None
    if kind is None:
        plan = await route(text)
        kind = plan["dispatch_kind"] if plan else classify(text)
    started = time.time()

    if kind == "setup":
        # Channels usually call setup_ha/setup_cameras separately for
        # progress UX; this path handles it in one shot.
        await setup_ha()
        return await setup_cameras()

    if kind == "scenario":
        # Deterministic: the router already parsed the trigger/device/schedule, so
        # translate + persist directly (no minder-scenario agent). Fall back to
        # the agent only if the router was unavailable.
        if plan:
            return await author_scenario(plan, text)
        return await create_scenario(text)

    if kind == "device":
        # The router already classified this and resolved the device + operation,
        # so control deterministically from the plan (no text re-parse / no verify).
        dev = plan.get("device", "") if plan else ""
        op = plan.get("operation", "") if plan else ""
        return await asyncio.to_thread(control_device, text, dev, op)

    if kind == "device_list":
        return await asyncio.to_thread(list_devices)

    if kind == "weather":
        # Weather is a deterministic, zero-argument lookup — the answer is fully
        # determined by the get-weather MCP tool's 'summary'. The 3B agent loop
        # adds only hallucination here (it invents a refusal instead of calling
        # the tool), so the backend relays the tool's summary directly. All
        # interpretation/phrasing still lives in the MCP server, not here.
        reply = await asyncio.to_thread(_weather_summary)
        if reply:
            return _envelope("weather", reply)
        return _envelope("weather", "I couldn't read the weather just now.")

    if kind == "camera_list":
        return await asyncio.to_thread(list_cameras)

    if kind == "vision" and plan:
        # Deterministic execution: the router parsed camera + subject; run
        # YOLO/VLM directly (no agent — proven unreliable at the tool call).
        if not _cameras_configured():
            return _envelope(
                "error",
                "No cameras configured yet. Send /start to discover cameras, "
                "or set them up at http://minder.local",
            )
        return await _dispatch_query(plan, started, text)

    if kind == "snapshot" and plan:
        # Deterministic: grab the router's camera frame(s) directly (no agent).
        if not _cameras_configured():
            return _envelope(
                "error",
                "No cameras configured yet. Send /start to discover cameras, "
                "or set them up at http://minder.local",
            )
        await asyncio.to_thread(_grab_frames, _resolve_cameras(plan)[:3])
        media = collect_media_since(started)
        if media:
            return _envelope("snapshot", "", media=media)
        return _envelope("snapshot", "Couldn't capture from that camera right now.")

    if kind in ("vision", "snapshot", "video"):
        # Serve-down fallback for vision (no plan); video still goes through the
        # agent (on-demand live clips aren't a deterministic grab yet).
        if not _cameras_configured():
            return _envelope(
                "error",
                "No cameras configured yet. Send /start to discover cameras, "
                "or set them up at http://minder.local",
            )

        context = build_context()
        enriched = f"{context}\n\n{text}" if context else text
        topology = {
            "vision": "minder-vision",
            "snapshot": "minder-snapshot",
            "video": "minder-video",
        }[kind]
        try:
            output = await asyncio.wait_for(run_topology(topology, enriched), timeout=180)
        except TimeoutError:
            return _envelope("error", "Request timed out — the AI model took too long. Try again.")

        media = collect_media_since(started)

        if kind == "vision":
            # The vision agent returns {"answer": "..."} via output_schema.
            reply = _extract_answer(output)
            if reply and not _looks_unhelpful(reply):
                return _envelope("vision", reply, media=media)
            # Fallback if the agent gave nothing usable: state the verdict
            # from the recorded detection, phrased to what the user asked.
            checks = _vision_checks_since(started)
            if checks:
                c = checks[-1]
                return _envelope("vision", _phrase_check(text, c), media=media)
            return _envelope(
                "vision",
                "I couldn't run that check. Tell me which camera, "
                "e.g. 'is anyone at the front door'.",
                media=media,
            )

        if media:
            return _envelope(kind, "", media=media)
        return _envelope(kind, "Couldn't capture from that camera. Try /cameras to see names.")

    # kind == "chat" (router said so, or the keyword fallback did) → open
    # conversation.
    # Conversational fallback
    prefix = f"{sender}: " if sender else ""
    context = build_context()
    enriched = f"{context}\n\n{prefix}{text}" if context else f"{prefix}{text}"
    try:
        response = await asyncio.wait_for(send_chat(enriched, source), timeout=180)
    except TimeoutError:
        return _envelope("error", "Request timed out. Try again.")
    except Exception:
        return _envelope(
            "error", "Minder's AI runtime isn't reachable right now. Try again in a moment."
        )
    formatted = response.replace("---", "").replace("***", "**").strip()
    return _envelope("chat", formatted or "Done.")
