# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  approval-policy.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel


class OnRevision(Enum):
    """
    Default reset_all. What a revision does to prior approvals: reset_all invalidates all; reconfirm_changed keeps approvals whose scope was not affected.
    """

    reset_all = "reset_all"
    reconfirm_changed = "reconfirm_changed"


class Identifier(RootModel[str]):
    root: str = Field(..., pattern="^[a-z][a-z0-9-]*$")


class Quorum1(Enum):
    """
    all = every role in the group must approve; any = one role suffices; {k-of: N} = any N distinct role-holders.
    """

    all = "all"
    any = "any"


class Quorum2(BaseModel):
    """
    all = every role in the group must approve; any = one role suffices; {k-of: N} = any N distinct role-holders.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    k_of: int = Field(..., alias="k-of", ge=1)


class Rule(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    scope: str = Field(
        ...,
        description="The authority exercised by this rule. Every role in `roles` must confer it (validated against the role registry at load time).",
        pattern="^[a-z][a-z0-9-]*:[a-z][a-z0-9-]*$",
    )
    roles: list[Identifier] = Field(
        ...,
        description="The group of roles that may exercise this rule's scope.",
        min_length=1,
    )
    quorum: Quorum1 | Quorum2 = Field(
        ...,
        description="all = every role in the group must approve; any = one role suffices; {k-of: N} = any N distinct role-holders.",
    )


class SwarmKitApprovalPolicy(BaseModel):
    """
    Per-gate multi-party approval policy: the rules (a governance scope + a group of roles + a quorum mode) that must ALL be satisfied for the gate to advance, plus segregation-of-duties controls. Embedded config consumed by approval gates — not a standalone artifact (no apiVersion/kind). See design/details/multi-party-approval.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    rules: list[Rule] = Field(
        ...,
        description="Every rule must be satisfied for the gate to advance.",
        min_length=1,
    )
    exclude_author: bool | None = Field(
        None,
        description="Default true. The identity that authored/submitted the artifact cannot approve it (segregation of duties).",
    )
    on_revision: OnRevision | None = Field(
        None,
        description="Default reset_all. What a revision does to prior approvals: reset_all invalidates all; reconfirm_changed keeps approvals whose scope was not affected.",
    )
    min_distinct_approvers: int | None = Field(
        None,
        description="Optional four-eyes floor: at least N distinct human identities must approve across all completed role-tasks, regardless of how roles overlap.",
        ge=1,
    )
