# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  contract.schema.json

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Party(RootModel[str]):
    root: str = Field(..., min_length=1)


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    name: str = Field(..., min_length=1)
    description: str = Field(..., min_length=10)


class AuthoredBy(Enum):
    human = "human"
    authored_by_swarm = "authored_by_swarm"
    derived_from_template = "derived_from_template"
    imported_from_registry = "imported_from_registry"
    vendor_published = "vendor_published"


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    authored_by: AuthoredBy
    authored_date: date | None = None
    version: str = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    registry: str | None = None
    vendor: str | None = None


class SwarmKitContract(BaseModel):
    """
    An integration contract: the agreed interface between two (or more) applications, identified by id. A first-class artifact so a pipeline's stage `locks` reference real contracts (a checked, pickable vocabulary) instead of free strings — no typo'd lock silently fails to serialise two requirements. The contract is not executed; it makes lock ids real and carries which apps it binds. See design/details/contract-registry.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    apiVersion: Literal["swarmkit/v1"]
    kind: Literal["Contract"]
    metadata: Metadata
    parties: list[Party] = Field(
        ...,
        description="The applications this contract binds (at least two) — what makes it a contract (an interface between apps). Drives the pipeline's contention/ownership display. App ids are free strings.",
        min_length=2,
    )
    interface: str | None = Field(
        None,
        description="Optional pointer to where the interface itself lives (an API/event schema). Not interpreted by core — documentation + a handle for reviewers.",
    )
    provenance: Provenance
