# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  executor-adapter.schema.json

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(
        ...,
        description="lowercase-kebab id; this is the executor `kind` an archetype selects.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    name: str = Field(..., min_length=1)
    description: str = Field(..., min_length=10)


class SuccessWhen(BaseModel):
    """
    Terminal success predicate. Core layers its semantic check (typed output + artifact-manifest match) on top — exit code alone is necessary, not sufficient.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    exit_code: int | None = None


class OnUnanswerable(Enum):
    """
    Interaction ceiling for a declarative adapter (RFC §5.2): deny refuses the out-of-grant action in place; abort terminates needs_approval. `relay` is Tier-1-only (needs bidirectional session control) and is not permitted here.
    """

    deny = "deny"
    abort = "abort"


class TelemetryGrade(Enum):
    """
    `opaque` (unobservable) adapters are denied by default (RFC decision 5); use requires explicit per-archetype opt-in.
    """

    normalized = "normalized"
    opaque = "opaque"


class Profile(Enum):
    files = "files"
    structured = "structured"
    media = "media"


class Artifacts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    profile: Profile | None = "files"


class OptionalArg(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    when: str = Field(
        ...,
        description="A substitution variable name (without braces), e.g. `budget.max_turns` or `config.model`.",
    )
    args: list[str]


class Launch(BaseModel):
    """
    How to launch the harness subprocess. `command` is argv (no shell); substitution is value-only.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    command: list[str] = Field(..., min_length=1)
    optional_args: list[OptionalArg] | None = Field(
        None,
        description="Arg groups appended only when the referenced variable is set; the whole group drops when it is empty.",
    )
    env: dict[str, str] | None = Field(
        None,
        description="Environment variables injected at launch. The only allowed secret is the model-provider credential (RFC §7): {credential.model_provider}. All other secrets are proxy-injected only (not here).",
    )


class Default(Enum):
    """
    The auth mode used when the workspace/archetype does not override.
    """

    api_key = "api_key"
    subscription = "subscription"


class AuthMode(BaseModel):
    """
    What an auth mode contributes to the launch. All parts optional — combine as the harness requires. Env and args are merged into the launch command/environment when this mode is active; credential_paths are provisioned into the sandbox.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    env: dict[str, str] | None = Field(
        None,
        description='Env vars this mode injects, e.g. {"ANTHROPIC_API_KEY": "{credential.model_provider}"}.',
    )
    args: list[str] | None = Field(
        None,
        description='Command args this mode appends, e.g. [--api-key, "{credential.model_provider}"] — for harnesses that take the key on the command line rather than the environment.',
    )
    credential_paths: list[str] | None = Field(
        None,
        description="Paths (files/dirs) holding the vendor's saved auth state to provision into the sandbox, e.g. ~/.claude — for subscription/CLI-login modes.",
    )


class Stream(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    format: Literal["jsonl"] = Field(
        ..., description="Line-delimited JSON only (RFC decision 1a)."
    )
    retain_raw: bool | None = Field(
        False,
        description="Tee each untranslated vendor line as exec.raw for a forensic trail.",
    )


class Event(Enum):
    started = "started"
    message = "message"
    tool_call = "tool_call"
    artifact = "artifact"
    usage = "usage"
    approval_requested = "approval_requested"
    input_requested = "input_requested"
    result = "result"
    raw = "raw"


class With(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    from_: str = Field(..., alias="from")
    map: str


class EmitSpec(BaseModel):
    """
    Emit one ExecEvent. `with` maps event fields to extracted values or literals.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    when: dict[str, str | float | bool | None] | None = Field(
        None,
        description="Optional per-item literal match (used inside a `for_each` to select array items by type).",
    )
    event: Event
    with_: dict[str, With | str | float | bool | None] | None = Field(
        None,
        alias="with",
        description='Event field -> extraction path ($.a.b) or literal. A field whose value is {"from": "$.x", "map": "status_map"} is translated through the named map (the only enum-translation primitive).',
    )


class Resume(BaseModel):
    """
    Makes resume-token support declarative: the captured session_id is replayed into the launch command on a retry/resume.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    arg: list[str] | None = Field(
        None,
        description='Args appended when resuming, e.g. [--resume, "{resume.token}"].',
    )


class AuthoredBy(Enum):
    human = "human"
    authored_by_swarm = "authored_by_swarm"
    derived_from_template = "derived_from_template"
    imported_from_registry = "imported_from_registry"
    vendor_published = "vendor_published"


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    authored_by: AuthoredBy
    authored_date: date | None = None
    version: str = Field(..., pattern="^[0-9]+\\.[0-9]+\\.[0-9]+$")
    registry: str | None = None
    vendor: str | None = None


class Modes(BaseModel):
    """
    The auth modes this adapter can run under, keyed by mode name; each value declares that mode's contribution to the launch.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    api_key: AuthMode | None = None
    subscription: AuthMode | None = None


class Auth(BaseModel):
    """
    Which authentication modes the harness supports (RFC decision 4), expressed generically. A mode contributes to the launch however the harness needs — env vars, extra command args, and/or provisioned credential paths — so auth may be an env var, a command flag, saved CLI credentials, or any combination; the engine has no per-mode special-casing. Both modes may be declared; `default` sets the mode used when the workspace/archetype does not override. In headless mode api_key takes precedence over subscription where both are usable.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    default: Default | None = Field(
        None,
        description="The auth mode used when the workspace/archetype does not override.",
    )
    modes: Modes | None = Field(
        None,
        description="The auth modes this adapter can run under, keyed by mode name; each value declares that mode's contribution to the launch.",
    )


class Rule(BaseModel):
    """
    One event-map rule: match a parsed JSON line, optionally iterate an array, capture state, and/or emit ExecEvents.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    when: dict[str, str | float | bool | None] | None = Field(
        None,
        description="Literal-equality match on dotted field paths of the parsed line (keys are dotted paths, values are the required literals). Empty/absent = matches every line.",
    )
    for_each: str | None = Field(
        None,
        description="A dotted path to an array; the rule's `emit` runs once per item, with `$.` resolving against the item.",
    )
    set: dict[str, str | float | bool | None] | None = Field(
        None,
        description="Capture values into adapter state (no event). The only recognized key is `session_id` (used for resume tokens).",
    )
    emit: list[EmitSpec] | None = None


class Spec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    launch: Launch
    auth: Auth | None = None
    stream: Stream
    event_map: list[Rule] = Field(..., min_length=1)
    status_map: dict[str, str] | None = Field(
        None,
        description="Vendor discriminator value -> ExecResultStatus (success|failure|budget_exceeded|cancelled|needs_approval|stalled). `_default` covers the rest.",
    )
    resume: Resume | None = None
    success_when: SuccessWhen | None = Field(
        None,
        description="Terminal success predicate. Core layers its semantic check (typed output + artifact-manifest match) on top — exit code alone is necessary, not sufficient.",
    )
    on_unanswerable: OnUnanswerable | None = Field(
        "abort",
        description="Interaction ceiling for a declarative adapter (RFC §5.2): deny refuses the out-of-grant action in place; abort terminates needs_approval. `relay` is Tier-1-only (needs bidirectional session control) and is not permitted here.",
    )
    telemetry_grade: TelemetryGrade | None = Field(
        "normalized",
        description="`opaque` (unobservable) adapters are denied by default (RFC decision 5); use requires explicit per-archetype opt-in.",
    )
    artifacts: Artifacts | None = None
    requires: Literal["code"] | None = Field(
        None,
        description="Present only when this adapter has hit the declarative DSL ceiling and must be implemented as a Tier-1 Python Executor instead. A validator/loader treats `requires: code` as 'not runnable declaratively'.",
    )


class SwarmKitExecutorAdapter(BaseModel):
    """
    A declarative harness adapter (design/details/executor-declarative-adapters-plan.md). Defines how to launch an external agentic harness as a subprocess and map its line-delimited JSON output into the normalized ExecEvent vocabulary — so a new harness is added as data (this artifact), with no Python and no runtime release. The DSL is deliberately minimal (RFC executor-abstraction.md decision 1a): JSONL streams only, literal-equality matching, dotted-path/for_each extraction, a named map for enum translation; anything past that ceiling declares `requires: code` and graduates to a Tier-1 Python Executor.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    apiVersion: Literal["swarmkit/v1"]
    kind: Literal["ExecutorAdapter"]
    metadata: Metadata
    spec: Spec
    provenance: Provenance
