# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  funnel.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Validate(BaseModel):
    """
    Layer 1 (deterministic, no LLM): structured-output validation with field-specific auto-correction. A shape auto-correction cannot repair is a retry — the judge never sees malformed input.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    schema_: str | None = Field(
        None,
        alias="schema",
        description="Path (workspace-relative) to a JSON Schema the artifact must satisfy.",
    )
    autocorrect: bool | None = Field(
        None,
        description="Default true. Re-prompt the drafter with field-specific corrections before treating an invalid shape as a retry.",
    )


class RouteBackAt(Enum):
    """
    Default high. Findings at or above this severity retry; lower findings attach and travel to the human.
    """

    low = "low"
    medium = "medium"
    high = "high"
    critical = "critical"


class Identifier(RootModel[str]):
    root: str = Field(..., pattern="^[a-z][a-z0-9-]*$")


class OnRevision(Enum):
    """
    Default reset_all. What a revision does to prior approvals: reset_all invalidates all; reconfirm_changed keeps approvals whose scope was not affected.
    """

    reset_all = "reset_all"
    reconfirm_changed = "reconfirm_changed"


class Quorum1(Enum):
    """
    all = every role in the group must approve; any = one role suffices; {k-of: N} = any N distinct role-holders.
    """

    all = "all"
    any = "any"


class Quorum2(BaseModel):
    """
    all = every role in the group must approve; any = one role suffices; {k-of: N} = any N distinct role-holders.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    k_of: int = Field(..., alias="k-of", ge=1)


class Judge(BaseModel):
    """
    Layer 2: an LLM-as-judge governance decision skill that scores the artifact against a rubric. Below `threshold` drives a bounded retry carrying the critique back to the drafter.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    skill: str = Field(
        ...,
        description="Decision-skill ID (category: decision), e.g. artifact-judge.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    rubric: str | None = Field(
        None,
        description="Path (workspace-relative) to the rubric the judge scores against.",
    )
    threshold: float | None = Field(
        None,
        description="Default 0.8. Judge score below this is a retry.",
        ge=0.0,
        le=1.0,
    )
    max_retries: int | None = Field(
        None,
        description="Default 2. Retries before the funnel escalates to a human with the last critique attached — it never drops or silently advances.",
        ge=0,
    )


class Review(BaseModel):
    """
    Layer 3 (optional; heavyweight gates only): an investigative harness reviewer. Findings at or above `route_back_at` retry; the rest attach to the human task.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    archetype: str = Field(
        ...,
        description="Reviewer archetype ID, e.g. architect-reviewer, security-consultant.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    read_scope: list[str] | None = Field(
        None,
        description="Read-only IAM scopes the reviewer is granted for its investigation.",
    )
    route_back_at: RouteBackAt | None = Field(
        None,
        description="Default high. Findings at or above this severity retry; lower findings attach and travel to the human.",
    )


class Rule(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    scope: str = Field(
        ...,
        description="The authority exercised by this rule. Every role in `roles` must confer it (validated against the role registry at load time).",
        pattern="^[a-z][a-z0-9-]*:[a-z][a-z0-9-]*$",
    )
    roles: list[Identifier] = Field(
        ...,
        description="The group of roles that may exercise this rule's scope.",
        min_length=1,
    )
    quorum: Quorum1 | Quorum2 = Field(
        ...,
        description="all = every role in the group must approve; any = one role suffices; {k-of: N} = any N distinct role-holders.",
    )


class ApprovalPolicy(BaseModel):
    """
    Mirrors SwarmKitApprovalPolicy (design/details/multi-party-approval.md): the rules that must ALL be satisfied for the human gate to advance, plus segregation-of-duties controls.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    rules: list[Rule] = Field(
        ...,
        description="Every rule must be satisfied for the gate to advance.",
        min_length=1,
    )
    exclude_author: bool | None = Field(
        None,
        description="Default true. The identity that authored the artifact cannot approve it (segregation of duties).",
    )
    on_revision: OnRevision | None = Field(
        None,
        description="Default reset_all. What a revision does to prior approvals: reset_all invalidates all; reconfirm_changed keeps approvals whose scope was not affected.",
    )
    min_distinct_approvers: int | None = Field(
        None,
        description="Optional four-eyes floor: at least N distinct human identities must approve across all completed role-tasks.",
        ge=1,
    )


class SwarmKitFunnel(BaseModel):
    """
    Per-artifact quality gate composition: chains structured-output validation -> LLM-as-judge -> optional harness review -> multi-party human approval into one reusable gate. Every layer is optional except `approve`; present layers run in fixed order (validate, judge, review, approve). The automated layers filter and drive a bounded retry loop but never decide — the only exit is through `approve`. Embedded config consumed by gate nodes — not a standalone artifact (no apiVersion/kind). See design/details/gate-funnel.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    validate_: Validate | None = Field(
        None,
        alias="validate",
        description="Layer 1 (deterministic, no LLM): structured-output validation with field-specific auto-correction. A shape auto-correction cannot repair is a retry — the judge never sees malformed input.",
    )
    judge: Judge | None = Field(
        None,
        description="Layer 2: an LLM-as-judge governance decision skill that scores the artifact against a rubric. Below `threshold` drives a bounded retry carrying the critique back to the drafter.",
    )
    review: Review | None = Field(
        None,
        description="Layer 3 (optional; heavyweight gates only): an investigative harness reviewer. Findings at or above `route_back_at` retry; the rest attach to the human task.",
    )
    approve: ApprovalPolicy = Field(
        ...,
        description="Layer 4 (required): the multi-party human approval set. The only exit from the funnel to `done`.",
    )
