# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  model-provider.schema.json

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(
        ...,
        description="lowercase-kebab id; this is the executor `kind` an archetype selects.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    name: str = Field(..., min_length=1)
    description: str = Field(..., min_length=10)


class AuthoredBy(Enum):
    human = "human"
    authored_by_swarm = "authored_by_swarm"
    derived_from_template = "derived_from_template"
    imported_from_registry = "imported_from_registry"
    vendor_published = "vendor_published"


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    authored_by: AuthoredBy
    authored_date: date | None = None
    version: str = Field(..., pattern="^[0-9]+\\.[0-9]+\\.[0-9]+$")
    registry: str | None = None
    vendor: str | None = None


class Auth(BaseModel):
    """
    One shape: a static key in a header. Absent means no auth — a local runtime. OAuth and service accounts are the requires-code case.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    api_key_env: str | None = Field(
        None,
        description="Environment variable holding the key. The provider registers only when it is set.",
        pattern="^[A-Z][A-Z0-9_]*$",
    )
    header: str | None = Field("Authorization", min_length=1)
    scheme: str | None = Field(
        "Bearer",
        description="Prefix before the key; empty string for a bare key (Azure's api-key header).",
    )


class Models(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    pattern: str | None = Field(
        None, description="What supports() accepts. Default comes from the family."
    )
    accept_any: bool | None = Field(
        None,
        description="Aggregators and local servers: the catalogue is unbounded and the server validates.",
    )


class Capabilities(BaseModel):
    """
    May only NARROW the family. A true the family does not offer is a load-time error.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    images: bool | None = None
    tools: bool | None = None
    streaming: bool | None = None
    structured_output: bool | None = None


class LiftToRootItem(RootModel[str]):
    root: str = Field(..., min_length=1)


class Options(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    lift_to_root: list[LiftToRootItem] | None = Field(
        None,
        description="Option keys moved from `options` to the payload root — Ollama's think and keep_alive. ollama family only.",
    )


class Spec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    extends: str = Field(
        ...,
        description="A wire-format family (openai-compatible, anthropic, google, ollama) or another provider's id. Resolved at load; the chain must end at a family and may not revisit an id.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    base_url: str | None = Field(
        None,
        description="Endpoint. ${VAR:-default} substitution applies.",
        min_length=1,
    )
    auth: Auth | None = None
    models: Models | None = None
    capabilities: Capabilities | None = None
    options: Options | None = None
    headers: dict[str, str] | None = Field(
        None,
        description="Static extra request headers, e.g. OpenRouter's HTTP-Referer.",
    )
    extra_body: dict[str, Any] | None = Field(
        None,
        description="Fields merged into the request body that the family's base API does not define, e.g. OpenRouter's usage.include. openai-compatible only.",
    )
    requires: Literal["code"] | None = Field(
        None,
        description="Declares this provider cannot be expressed declaratively. Load refuses it with the reason — the ceiling fails loudly rather than half-working.",
    )


class SwarmKitModelProvider(BaseModel):
    """
    A declarative model provider (design/details/declarative-model-providers.md). A provider is DATA: a base URL, an auth shape, a model catalogue, capabilities and request quirks, layered over a wire-format FAMILY that stays code (openai-compatible, anthropic, google, ollama). `extends` names a family or another provider; fields merge one hop at a time. Capabilities may only NARROW what the family offers. Anything past the DSL's ceiling declares `requires: code` and is refused at load rather than half-working.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    apiVersion: Literal["swarmkit/v1"]
    kind: Literal["ModelProvider"]
    metadata: Metadata
    spec: Spec
    provenance: Provenance
