# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  role-registry.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Scope(RootModel[str]):
    root: str = Field(
        ...,
        description="A governance scope of the form `<resource>:<action>`, e.g. `design:approve`. Any scope conferred by a role is a human-identity scope — the policy engine refuses to grant it to a non-human (agent) principal.",
        pattern="^[a-z][a-z0-9-]*:[a-z][a-z0-9-]*$",
    )


class Member(RootModel[str]):
    root: str = Field(..., min_length=1)


class Role(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    members: list[Member] = Field(
        ...,
        description="Human identity references that hold this role. May be empty for an unstaffed role; a gate requiring an unstaffed role cannot reach quorum.",
    )
    scopes: list[Scope] = Field(
        ...,
        description="Governance scopes this role confers. A role carries many scopes so a handover is a single membership edit.",
        min_length=1,
    )


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    name: str = Field(..., min_length=1)
    description: str | None = None


class SwarmKitRoleRegistry(BaseModel):
    """
    Workspace-level IAM registry mapping roles to the human identities that hold them and the governance scopes they confer. A role carries many scopes (RBAC: identity -> role -> scopes), so membership lives in one place per person. Consumed by multi-party approval gates. See design/details/multi-party-approval.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    apiVersion: Literal["swarmkit/v1"]
    kind: Literal["RoleRegistry"]
    metadata: Metadata
    roles: list[Role] = Field(
        ...,
        description="The roles in this workspace. Role ids must be unique (enforced at load time — JSON Schema cannot express object-field uniqueness).",
        min_length=1,
    )
