# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  skill.schema.json

from __future__ import annotations

from datetime import date
from enum import Enum, StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Category(StrEnum):
    """
    Runtime semantics differ by category (design §6.2).
    """

    capability = "capability"
    decision = "decision"
    coordination = "coordination"
    persistence = "persistence"


class Identifier(RootModel[str]):
    root: str = Field(..., pattern="^[a-z][a-z0-9-]*$")


class IamScope(RootModel[str]):
    root: str = Field(
        ...,
        description="namespace:action — e.g. repo:read, github:write, skills:activate, mcp_servers:*",
        pattern="^[a-z][a-z0-9_-]*:[a-z*][a-z0-9_*-]*$",
    )


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    name: str = Field(..., min_length=1)
    description: str = Field(..., min_length=10)


class Type(StrEnum):
    string = "string"
    number = "number"
    integer = "integer"
    boolean = "boolean"
    enum = "enum"
    object = "object"
    array = "array"


class Implementation1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["mcp_tool"]
    server: str = Field(..., min_length=1)
    tool: str = Field(..., min_length=1)
    arguments: dict[str, Any] | None = None


class Implementation2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["llm_prompt"]
    model: dict[str, Any] | None = None
    prompt: str = Field(..., min_length=1)


class Strategy(StrEnum):
    parallel_consensus = "parallel-consensus"
    sequential = "sequential"
    custom = "custom"


class Implementation3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["composed"]
    composes: list[Identifier] = Field(..., min_length=1)
    strategy: Strategy | None = None


class Implementation4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["command"]
    pack: str = Field(..., min_length=1)
    command: str = Field(..., min_length=1)


class OnUnanswerable(StrEnum):
    """
    What happens when the other agent asks a question — the same words a harness adapter uses for a mid-run request. relay: a person answers through the review queue (bounded wait, never hangs). abort: the call fails with the question as the reason. agent: the question is the tool result and the calling agent answers it, bounded by max_agent_answers and audited; past the budget it relays. A human gate on the other side is never the agent's to resolve, whatever this says.
    """

    agent = "agent"
    relay = "relay"
    abort = "abort"


class Permission(StrEnum):
    """
    Governance tier for the call, as an MCP server's `permission` is for its tools.
    """

    open = "open"
    cautious = "cautious"
    strict = "strict"
    readonly = "readonly"


class Effects(StrEnum):
    """
    What calling this agent does to the world. Under `readonly`, only `read` is allowed — `unknown` is denied, fail-closed, as for MCP tools.
    """

    read = "read"
    write = "write"
    unknown = "unknown"


class Implementation5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["agent"]
    topology: str = Field(
        ...,
        description="A topology in this workspace. Runs as a child job of the caller's run (same correlation, parent_job_id set); no network.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    card_url: str | None = Field(
        None,
        description="A remote agent's Agent Card URL (usually .../.well-known/agent-card.json). The card's `url` is where the task API is called.",
        pattern="^https?://",
    )
    skill_id: str | None = Field(
        None,
        description="Remote only: which of the card's skills this skill invokes (sent as message.metadata.skill). Omitted: the card's first skill.",
    )
    credentials_ref: str | None = Field(
        None,
        description="Remote only: a workspace `credentials` entry, resolved by the credential service and sent as a bearer token.",
    )
    timeout_s: int | None = Field(
        600,
        description="How long to wait for the other agent's task to finish before the call fails.",
        ge=1,
    )
    on_unanswerable: OnUnanswerable | None = Field(
        "agent",
        description="What happens when the other agent asks a question — the same words a harness adapter uses for a mid-run request. relay: a person answers through the review queue (bounded wait, never hangs). abort: the call fails with the question as the reason. agent: the question is the tool result and the calling agent answers it, bounded by max_agent_answers and audited; past the budget it relays. A human gate on the other side is never the agent's to resolve, whatever this says.",
    )
    max_agent_answers: int | None = Field(
        2,
        description="Under `agent`: how many questions the calling agent may answer on one task before the next one is relayed to a person.",
        ge=0,
    )
    permission: Permission | None = Field(
        "cautious",
        description="Governance tier for the call, as an MCP server's `permission` is for its tools.",
    )
    effects: Effects | None = Field(
        "unknown",
        description="What calling this agent does to the world. Under `readonly`, only `read` is allowed — `unknown` is denied, fail-closed, as for MCP tools.",
    )


class Implementation6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Literal["agent"]
    topology: str | None = Field(
        None,
        description="A topology in this workspace. Runs as a child job of the caller's run (same correlation, parent_job_id set); no network.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    card_url: str = Field(
        ...,
        description="A remote agent's Agent Card URL (usually .../.well-known/agent-card.json). The card's `url` is where the task API is called.",
        pattern="^https?://",
    )
    skill_id: str | None = Field(
        None,
        description="Remote only: which of the card's skills this skill invokes (sent as message.metadata.skill). Omitted: the card's first skill.",
    )
    credentials_ref: str | None = Field(
        None,
        description="Remote only: a workspace `credentials` entry, resolved by the credential service and sent as a bearer token.",
    )
    timeout_s: int | None = Field(
        600,
        description="How long to wait for the other agent's task to finish before the call fails.",
        ge=1,
    )
    on_unanswerable: OnUnanswerable | None = Field(
        "agent",
        description="What happens when the other agent asks a question — the same words a harness adapter uses for a mid-run request. relay: a person answers through the review queue (bounded wait, never hangs). abort: the call fails with the question as the reason. agent: the question is the tool result and the calling agent answers it, bounded by max_agent_answers and audited; past the budget it relays. A human gate on the other side is never the agent's to resolve, whatever this says.",
    )
    max_agent_answers: int | None = Field(
        2,
        description="Under `agent`: how many questions the calling agent may answer on one task before the next one is relayed to a person.",
        ge=0,
    )
    permission: Permission | None = Field(
        "cautious",
        description="Governance tier for the call, as an MCP server's `permission` is for its tools.",
    )
    effects: Effects | None = Field(
        "unknown",
        description="What calling this agent does to the world. Under `readonly`, only `read` is allowed — `unknown` is denied, fail-closed, as for MCP tools.",
    )


class Iam(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    required_scopes: list[IamScope] | None = None


class Backoff(StrEnum):
    exponential = "exponential"
    linear = "linear"
    none = "none"


class Retry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    attempts: int | None = Field(None, ge=0)
    backoff: Backoff | None = None


class OnFailure(StrEnum):
    escalate_to_human = "escalate_to_human"
    fail = "fail"
    retry = "retry"
    fallback = "fallback"


class Constraints(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    max_latency_ms: int | None = Field(None, ge=1)
    timeout_seconds: int | None = Field(None, ge=1)
    retry: Retry | None = None
    on_failure: OnFailure | None = None


class LogInputs(StrEnum):
    """
    How much of the skill's input to log. Default varies by category: decision=full, capability=summary.
    """

    full = "full"
    summary = "summary"
    none = "none"


class LogOutputs(StrEnum):
    """
    How much of the skill's output to log.
    """

    full = "full"
    summary = "summary"
    none = "none"


class Audit(BaseModel):
    """
    Controls what gets logged when this skill executes. Per-skill privacy/compliance control.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    log_inputs: LogInputs | None = Field(
        None,
        description="How much of the skill's input to log. Default varies by category: decision=full, capability=summary.",
    )
    log_outputs: LogOutputs | None = Field(
        None, description="How much of the skill's output to log."
    )
    redact: list[str] | None = Field(
        None,
        description="JSON paths to redact from logged inputs/outputs (e.g. '$.password', '$.api_key').",
    )


class AuthoredBy(StrEnum):
    human = "human"
    authored_by_swarm = "authored_by_swarm"
    derived_from_template = "derived_from_template"
    imported_from_registry = "imported_from_registry"
    vendor_published = "vendor_published"


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    authored_by: AuthoredBy
    authored_date: date | None = None
    version: str = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    requires_runtime: str | None = Field(None, pattern="^>=\\d+\\.\\d+\\.\\d+$")
    registry: str | None = None
    vendor: str | None = None


class SwarmKitSkill(BaseModel):
    """
    A discrete capability an agent can exercise. See design §6 and design/details/skill-schema-v1.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    apiVersion: Literal["swarmkit/v1"]
    kind: Literal["Skill"]
    metadata: Metadata
    category: Category = Field(
        ..., description="Runtime semantics differ by category (design §6.2)."
    )
    inputs: dict[str, Any] | None = Field(
        None,
        description="JSON Schema (draft 2020-12) defining the skill's input shape.",
    )
    outputs: dict[str, Any] | None = Field(
        None,
        description="JSON Schema defining the skill's output shape. Passed to providers for structured generation (Tier 0) and used for deterministic validation (Tier 1). See design/details/structured-output-governance.md.",
    )
    implementation: (
        Implementation1
        | Implementation2
        | Implementation3
        | Implementation4
        | Implementation5
        | Implementation6
    )
    iam: Iam | None = None
    constraints: Constraints | None = None
    audit: Audit | None = None
    provenance: Provenance


class FieldModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    type: Type
    required: bool | None = None
    description: str | None = None
    values: list[Any] | None = Field(
        None, description="Required when type=enum.", min_length=1
    )
    range: list[float] | None = Field(
        None,
        description="[min, max] — only for number/integer.",
        max_length=2,
        min_length=2,
    )
    items: FieldModel | None = Field(None, description="Required when type=array.")
    properties: dict[str, FieldModel] | None = Field(
        None, description="Optional when type=object."
    )


FieldModel.model_rebuild()
