# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  stage-graph.schema.json

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Identifier(RootModel[str]):
    root: str = Field(..., pattern="^[a-z][a-z0-9-]*$")


class Event(RootModel[str]):
    root: str = Field(
        ...,
        description="An external enterprise event (Jira/CI/Git/SAST) or a signal emitted by a prior stage's `success`. The controller treats both uniformly.",
        pattern="^[a-z][a-z0-9._-]*$",
    )


class Stage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    topology: str = Field(
        ...,
        description="The topology this stage kicks as a bounded run.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    when: list[Event] | None = Field(
        None,
        description="Entry event(s): the stage starts when one of these arrives (external event or a prior stage's signal). Named `when` (not `on`) because YAML 1.1 parsers coerce a bare `on` key to a boolean.",
    )
    success: str | None = Field(
        None,
        description="The signal emitted on clean stage completion (drives the next stage's `on`).",
        pattern="^[a-z][a-z0-9._-]*$",
    )
    locks: list[Identifier] | None = Field(
        None,
        description="Integration contracts (by id) this stage holds — acquired all-or-none in fixed order before the run, released on `release_locks_on`. Each references a Contract artifact (design/details/contract-registry.md).",
    )
    release_locks_on: str | None = Field(
        None,
        description="The signal whose arrival releases this stage's locks (e.g. hold the contract through approval, then release).",
        pattern="^[a-z][a-z0-9._-]*$",
    )
    gate: str | None = Field(
        None,
        description="A Funnel gate the stage's run parks on; the controller emits `success` when it resolves.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    compensation: str | None = Field(
        None,
        description="Topology run to unwind this stage if the requirement is cancelled after the stage passed.",
        pattern="^[a-z][a-z0-9-]*$",
    )


class Loop(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    when: str = Field(
        ...,
        description="The event that triggers this cross-stage edge (e.g. defect.raised).",
        pattern="^[a-z][a-z0-9._-]*$",
    )
    to: str = Field(
        ...,
        description="The stage id this event routes to (must be a stage in this graph).",
        pattern="^[a-z][a-z0-9-]*$",
    )


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    name: str = Field(..., min_length=1)
    description: str = Field(..., min_length=10)


class AuthoredBy(Enum):
    human = "human"
    authored_by_swarm = "authored_by_swarm"
    derived_from_template = "derived_from_template"
    imported_from_registry = "imported_from_registry"
    vendor_published = "vendor_published"


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    authored_by: AuthoredBy
    authored_date: date | None = None
    version: str = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    registry: str | None = None
    vendor: str | None = None


class SwarmKitStageGraph(BaseModel):
    """
    A pipeline as data: an ordered set of bounded stages a controller sequences as a saga, correlated by requirement_id and advanced by external events or prior-stage signals. Each stage kicks a SwarmKit topology run; a stage may hold integration-contract locks, park on a gate (a Funnel), and declare a compensation topology for cancellation. `loops` are cross-stage edges (the defect cycle). The controller (a reference component, not the runtime) owns the durable weeks-long state; SwarmKit only runs the bounded stages. See design/details/pipeline-controller.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    apiVersion: Literal["swarmkit/v1"]
    kind: Literal["StageGraph"]
    metadata: Metadata
    stages: list[Stage] = Field(
        ...,
        description="The pipeline's stages. Stage ids must be unique.",
        min_length=1,
    )
    loops: list[Loop] | None = Field(
        None,
        description="Cross-stage edges (e.g. the defect cycle): an inbound event routes to a stage.",
    )
    provenance: Provenance
