# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  topology.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Identifier(RootModel[str]):
    root: str = Field(
        ...,
        description="Lowercase kebab. Must start with a letter.",
        pattern="^[a-z][a-z0-9-]*$",
    )


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    name: str = Field(
        ...,
        description="Lowercase kebab. Must start with a letter.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    version: str = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    description: str | None = None


class Mode(Enum):
    """
    Execution mode (design §14.1).
    """

    one_shot = "one-shot"
    persistent = "persistent"
    scheduled = "scheduled"


class Storage(Enum):
    sqlite = "sqlite"
    postgres = "postgres"


class Checkpointing(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    storage: Storage | None = None


class Runtime(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    mode: Mode | None = Field(None, description="Execution mode (design §14.1).")
    max_concurrent_tasks: int | None = Field(None, ge=1)
    task_timeout_seconds: int | None = Field(None, ge=1)
    checkpointing: Checkpointing | None = None


class Role(Enum):
    root = "root"
    leader = "leader"
    worker = "worker"


class Role2(Enum):
    leader = "leader"
    worker = "worker"


class Model(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    provider: str | None = Field(
        None,
        description="Typically anthropic | openai | google | azure | local | custom.",
    )
    name: str | None = None
    temperature: float | None = Field(None, ge=0.0, le=2.0)
    max_tokens: int | None = Field(None, ge=1)


class Prompt(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    system: str | None = None
    persona: str | None = None


class Iam(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    base_scope: list[str] | None = None
    elevated_scopes: list[str] | None = None


class Level(Enum):
    minimal = "minimal"
    standard = "standard"
    detailed = "detailed"


class Audit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    level: Level | None = None
    storage: Storage | None = None
    retention_days: int | None = Field(None, ge=1)


class SkillGapLogging(BaseModel):
    """
    See design §12.1.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    enabled: bool | None = None
    surface_threshold: int | None = Field(None, ge=1)


class Artifacts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    knowledge_bases: list[dict[str, Any]] | None = None
    review_queues: list[dict[str, Any]] | None = None
    audit: Audit | None = None
    skill_gap_logging: SkillGapLogging | None = Field(
        None, description="See design §12.1."
    )


class SwarmKitTopology(BaseModel):
    """
    A complete swarm definition. See design §10 and design/details/topology-schema-v1.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    apiVersion: Literal["swarmkit/v1"] = Field(
        ..., description="Schema version. Breaking changes bump this major."
    )
    kind: Literal["Topology"]
    metadata: Metadata
    runtime: Runtime | None = None
    agents: Agents
    artifacts: Artifacts | None = None


class Agents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    root: Root


class Agent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(
        ...,
        description="Lowercase kebab. Must start with a letter.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    role: Role
    archetype: str | None = Field(
        None,
        description="Lowercase kebab. Must start with a letter.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    model: Model | None = None
    prompt: Prompt | None = None
    skills: list[Identifier] | None = Field(
        None,
        description="Skill IDs (design §6.1). Replaces the archetype's skill list when present.",
    )
    skills_additional: list[Identifier] | None = Field(
        None, description="Skills merged onto the archetype defaults (design §6.6)."
    )
    iam: Iam | None = None
    children: list[ChildAgent] | None = Field(
        None,
        description="Nested agents. Tree structure, one parent per agent (design §5.2).",
    )


class Root(Agent):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    role: Literal["root"] = "root"


class ChildAgent(Agent):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    role: Role2 | None = None


SwarmKitTopology.model_rebuild()
Agents.model_rebuild()
Agent.model_rebuild()
Root.model_rebuild()
ChildAgent.model_rebuild()
