# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  topology.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Identifier(RootModel[str]):
    root: str = Field(
        ...,
        description="Lowercase kebab. Must start with a letter.",
        pattern="^[a-z][a-z0-9-]*$",
    )


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    name: str = Field(
        ...,
        description="Lowercase kebab. Must start with a letter.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    version: str = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    description: str | None = None


class Mode(Enum):
    """
    Execution mode (design §14.1).
    """

    one_shot = "one-shot"
    persistent = "persistent"
    scheduled = "scheduled"


class Storage(Enum):
    sqlite = "sqlite"
    postgres = "postgres"


class Checkpointing(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    storage: Storage | None = None


class Role(Enum):
    root = "root"
    leader = "leader"
    worker = "worker"


class Role2(Enum):
    leader = "leader"
    worker = "worker"


class Model(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    provider: str | None = Field(
        None,
        description="Typically anthropic | openai | google | azure | local | custom.",
    )
    name: str | None = None
    temperature: float | None = Field(None, ge=0.0, le=2.0)
    max_tokens: int | None = Field(None, ge=1)


class Prompt(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    system: str | None = None
    persona: str | None = None


class Iam(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    base_scope: list[str] | None = None
    elevated_scopes: list[str] | None = None


class Level(Enum):
    minimal = "minimal"
    standard = "standard"
    detailed = "detailed"


class Audit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    level: Level | None = None
    storage: Storage | None = None
    retention_days: int | None = Field(None, ge=1)


class SkillGapLogging(BaseModel):
    """
    See design §12.1.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    enabled: bool | None = None
    surface_threshold: int | None = Field(None, ge=1)


class Artifacts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    knowledge_bases: list[dict[str, Any]] | None = None
    review_queues: list[dict[str, Any]] | None = None
    audit: Audit | None = None
    skill_gap_logging: SkillGapLogging | None = Field(
        None, description="See design §12.1."
    )


class OnDrift(Enum):
    """
    Strategy when drift exceeds threshold. log=audit only, warn=log+event, nudge=inject refocus message.
    """

    log = "log"
    warn = "warn"
    nudge = "nudge"


class IntentMonitoring(BaseModel):
    """
    Optional intent drift detection. Monitors semantic drift from the original goal. See design/details/intent-drift-detection.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    enabled: bool | None = Field(
        None, description="Enable drift detection for this topology."
    )
    threshold: float | None = Field(
        None,
        description="Drift score above which action is taken. Default: 0.75. Range guide: 0.5=aggressive, 0.75=balanced, 0.9=permissive.",
        ge=0.0,
        le=2.0,
    )
    on_drift: OnDrift | None = Field(
        None,
        description="Strategy when drift exceeds threshold. log=audit only, warn=log+event, nudge=inject refocus message.",
    )


class Planning(BaseModel):
    """
    Controls task planning and scope behavior for leader agents. When set, the compiler enforces structured planning instead of relying on prompt instructions.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    scope_required: bool | None = Field(
        False,
        description="Leaders must call create-scope before synthesis. Blocks synthesis if no scope exists.",
    )
    two_phase: bool | None = Field(
        False,
        description="Enforce two-phase planning: Phase 1 (research) → create-scope → Phase 2 (targeted tasks). The compiler auto-injects checkpoint prompts.",
    )


class Synthesis(BaseModel):
    """
    Topology-level synthesis config. Overrides workspace-level synthesis. When set, the compiler invokes a large-context model with all research results instead of having the architect write the document.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    provider: str | None = Field(
        None, description="Model provider ID. Overrides workspace synthesis provider."
    )
    model: str | None = Field(
        None, description="Model name. Overrides workspace synthesis model."
    )
    prompt: str | None = Field(
        None,
        description="Custom system prompt for the synthesizer. Overrides workspace-level prompt.",
    )


class Trigger(Enum):
    """
    When the skill fires: pre_input (before agent runs), post_output (after agent output), checkpoint (between task batches), pre_synthesis (before final synthesis).
    """

    pre_input = "pre_input"
    post_output = "post_output"
    checkpoint = "checkpoint"
    pre_synthesis = "pre_synthesis"


class DecisionSkillBinding(BaseModel):
    """
    Binds a decision skill to a trigger point.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., description="Decision skill ID.", pattern="^[a-z][a-z0-9-]*$")
    trigger: Trigger = Field(
        ...,
        description="When the skill fires: pre_input (before agent runs), post_output (after agent output), checkpoint (between task batches), pre_synthesis (before final synthesis).",
    )
    scope: str | None = Field(
        None, description="Comma-separated agent IDs. Default '*' = all agents."
    )
    required: bool | None = Field(
        True, description="Set false to disable an inherited workspace binding."
    )
    config: dict[str, Any] | None = Field(
        None, description="Skill-specific configuration."
    )


class Runtime(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    mode: Mode | None = Field(None, description="Execution mode (design §14.1).")
    max_concurrent_tasks: int | None = Field(None, ge=1)
    task_timeout_seconds: int | None = Field(None, ge=1)
    planning: Planning | None = None
    synthesis: Synthesis | None = None
    checkpointing: Checkpointing | None = None


class Governance(BaseModel):
    """
    Topology-level governance overrides. Inherits from workspace governance; entries here override or extend by id.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    decision_skills: list[DecisionSkillBinding] | None = Field(
        None,
        description="Decision skill bindings that override or extend workspace-level bindings. Same id = override, new id = extend, required: false = disable inherited.",
    )


class SwarmKitTopology(BaseModel):
    """
    A complete swarm definition. See design §10 and design/details/topology-schema-v1.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    apiVersion: Literal["swarmkit/v1"] = Field(
        ..., description="Schema version. Breaking changes bump this major."
    )
    kind: Literal["Topology"]
    metadata: Metadata
    runtime: Runtime | None = None
    agents: Agents
    artifacts: Artifacts | None = None
    intent_monitoring: IntentMonitoring | None = None
    governance: Governance | None = None


class Agents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    root: Root


class Agent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(
        ...,
        description="Lowercase kebab. Must start with a letter.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    role: Role
    archetype: str | None = Field(
        None,
        description="Lowercase kebab. Must start with a letter.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    model: Model | None = None
    prompt: Prompt | None = None
    skills: list[Identifier] | None = Field(
        None,
        description="Skill IDs (design §6.1). Replaces the archetype's skill list when present.",
    )
    skills_additional: list[Identifier] | None = Field(
        None, description="Skills merged onto the archetype defaults (design §6.6)."
    )
    iam: Iam | None = None
    output_schema: dict[str, Any] | None = None
    intent_monitoring: IntentMonitoring | None = None
    children: list[ChildAgent] | None = Field(
        None,
        description="Nested agents. Tree structure, one parent per agent (design §5.2).",
    )


class Root(Agent):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    role: Literal["root"] = "root"


class ChildAgent(Agent):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    role: Role2 | None = None
    depends_on: list[str] | None = Field(
        None,
        description="Agent IDs that must complete before this agent runs. Enables DAG-based execution ordering.",
    )


SwarmKitTopology.model_rebuild()
Agents.model_rebuild()
Agent.model_rebuild()
Root.model_rebuild()
ChildAgent.model_rebuild()
