# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  workspace.schema.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    name: str = Field(..., min_length=1)
    description: str | None = None
    annotations: dict[str, str] | None = Field(
        None,
        description="Arbitrary key-value metadata the runtime ignores. For enterprise use: cost_center, team, environment, compliance tags, etc.",
    )


class OrgOrTeam(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    name: str | None = None


class Provider(Enum):
    """
    GovernanceProvider implementation (design §8.5).
    """

    agt = "agt"
    mock = "mock"
    custom = "custom"


class PolicyLanguage(Enum):
    """
    §21 open question — default yaml for v1.0.
    """

    yaml = "yaml"
    rego = "rego"
    cedar = "cedar"


class Limits(BaseModel):
    """
    Circuit breaker thresholds. Prevents runaway execution and cost overruns.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    max_steps_per_agent: int | None = Field(
        None,
        description="Maximum execution steps per individual agent before abort.",
        ge=1,
    )
    max_steps_per_run: int | None = Field(
        None,
        description="Maximum total steps across all agents in a single run. Default: 500.",
        ge=1,
    )
    max_cost_per_run_usd: float | None = Field(
        None,
        description="Maximum estimated LLM cost (USD) per run before abort.",
        ge=0.0,
    )


class Provider1(Enum):
    """
    Human-identity provider (design §16.1).
    """

    builtin = "builtin"
    auth0 = "auth0"
    okta = "okta"
    google = "google"
    azure_ad = "azure-ad"
    oidc = "oidc"


class Identity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    provider: Provider1 = Field(
        ..., description="Human-identity provider (design §16.1)."
    )
    config: dict[str, Any] | None = None


class ModelProviderRegistration(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    class_: str = Field(
        ..., alias="class", description="Fully-qualified Python class path."
    )
    provider_id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    config: dict[str, Any] | None = None


class Source(Enum):
    env = "env"
    file = "file"
    hashicorp_vault = "hashicorp-vault"
    aws_secrets_manager = "aws-secrets-manager"
    gcp_secret_manager = "gcp-secret-manager"
    azure_key_vault = "azure-key-vault"
    plugin = "plugin"


class CredentialRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    source: Source
    provider_id: str | None = Field(
        None,
        description="Required when source=plugin. Names the registered SecretsProvider.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    config: dict[str, Any] = Field(
        ...,
        description="Provider-specific configuration. Runtime validates shape per source.",
    )


class Transport(Enum):
    stdio = "stdio"
    http = "http"


class Permission(Enum):
    """
    Governance permission tier for this server's tools. open: skip governance checks. cautious (default): reads auto-approved, writes go through governance. strict: all calls require explicit approval. readonly: write operations denied.
    """

    open = "open"
    cautious = "cautious"
    strict = "strict"
    readonly = "readonly"


class PermissionOverrides(Enum):
    open = "open"
    cautious = "cautious"
    strict = "strict"
    readonly = "readonly"


class Effects(Enum):
    read = "read"
    write = "write"


class McpServer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    transport: Transport
    command: list[str] | None = Field(
        None, description="Required when transport=stdio."
    )
    endpoint: str | None = Field(None, description="Required when transport=http.")
    env: dict[str, str] | None = Field(
        None,
        description="Environment variables passed to a stdio server. Values support ${VAR} expansion from the runtime process environment. Use `credentials_ref` for secrets; `env` is for configuration.",
    )
    cwd: str | None = Field(
        None,
        description="Working directory for stdio servers. Supports ${VAR} expansion. Defaults to workspace root.",
    )
    credentials_ref: str | None = None
    sandboxed: bool | None = Field(
        None, description="True forces Docker-or-equivalent isolation (design §8.8)."
    )
    sandbox_image: str | None = Field(
        None,
        description="Docker image for sandboxed servers. Defaults to swarmkit-mcp-sandbox (Python + mcp SDK). Use node:22-slim for Node.js servers.",
    )
    permission: Permission | None = Field(
        "cautious",
        description="Governance permission tier for this server's tools. open: skip governance checks. cautious (default): reads auto-approved, writes go through governance. strict: all calls require explicit approval. readonly: write operations denied.",
    )
    permission_overrides: dict[str, PermissionOverrides] | None = Field(
        None,
        description="Per-tool permission overrides. Keys are MCP tool names, values are permission tiers that override the server default.",
    )
    effects: dict[str, Effects] | None = Field(
        None,
        description="Whether each tool reads or writes, keyed by MCP tool name. Consulted by `permission: readonly`, which allows a tool only when it is known to read. Declared here wins over the server's own `readOnlyHint` annotation, because this is the half the operator controls; a tool with neither is `unknown` and is denied under readonly rather than guessed at. Until 1.199.0 write-ness was inferred by substring-scanning the tool name, which denied `get_dataset` and `read_asset` on 'set' and let `truncate_table` and `purge_cache` through.",
    )


class Backend(Enum):
    """
    Checkpointer backend. Defaults to sqlite at .swarmkit/state/checkpoints.db.
    """

    sqlite = "sqlite"
    postgres = "postgres"


class Checkpoints(BaseModel):
    """
    LangGraph run-state checkpointer. The one block that does NOT inherit storage.runtime: postgres here needs `pip install 'swarmkit-runtime[postgres]'`, so it is opt-in rather than implied.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    backend: Backend | None = Field(
        "sqlite",
        description="Checkpointer backend. Defaults to sqlite at .swarmkit/state/checkpoints.db.",
    )
    path: str | None = None
    url: str | None = Field(
        None,
        description="Connection URL for the postgres backend. Supports ${ENV_VAR} and ${ENV_VAR:-default} interpolation. Optional: inherits storage.runtime.url when omitted.",
    )


class Backend1(Enum):
    """
    Audit backend. Defaults to whatever storage.runtime resolves to. ('agt' was accepted here until 1.130.0, but no writer ever implemented it — selecting it silently wrote sqlite.)
    """

    sqlite = "sqlite"
    postgres = "postgres"


class Audit(BaseModel):
    """
    Append-only audit trail. Inherits storage.runtime unless it overrides it.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    backend: Backend1 | None = Field(
        None,
        description="Audit backend. Defaults to whatever storage.runtime resolves to. ('agt' was accepted here until 1.130.0, but no writer ever implemented it — selecting it silently wrote sqlite.)",
    )
    retention_days: int | None = Field(None, ge=1)
    url: str | None = Field(
        None,
        description="Connection URL for the postgres backend. Supports ${ENV_VAR} and ${ENV_VAR:-default} interpolation. Optional: inherits storage.runtime.url when omitted.",
    )


class Backend2(Enum):
    database = "database"
    filesystem = "filesystem"
    s3 = "s3"


class Artifacts(BaseModel):
    """
    Where pipeline stage outputs live. Defaults to `database` on the storage.runtime engine. Read by the runtime since the bundled orchestrator shipped, but undeclarable until 1.130.0 — `additionalProperties: false` rejected the very key the code looked for.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    backend: Backend2 | None = "database"
    path: str | None = Field(
        None,
        description="filesystem backend: root directory. Defaults to .swarmkit/artifacts.",
    )
    bucket: str | None = Field(
        None, description="s3 backend: bucket name (requires the boto3 optional dep)."
    )
    prefix: str | None = Field("artifacts", description="s3 backend: key prefix.")
    database_url: str | None = Field(
        None, description="database backend: override the inherited connection URL."
    )


class Backend3(Enum):
    """
    Storage backend. sqlite (default, zero config) or postgres (production, shared).
    """

    sqlite = "sqlite"
    postgres = "postgres"


class Runtime(BaseModel):
    """
    Backend for jobs, conversations, usage, pipeline sagas, artifacts, fleet enrollment and governed memory. Every other storage block inherits this one unless it overrides it. Defaults to sqlite at .swarmkit/store.sqlite.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    backend: Backend3 | None = Field(
        "sqlite",
        description="Storage backend. sqlite (default, zero config) or postgres (production, shared).",
    )
    url: str | None = Field(
        None,
        description="Connection URL for the postgres backend. Supports ${ENV_VAR} and ${ENV_VAR:-default} interpolation. May also be supplied as SWARMKIT_STORE_URL or DATABASE_URL, which take precedence over this file.",
    )


class DefaultBackend(Enum):
    sqlite = "sqlite"
    postgres = "postgres"


class KnowledgeBases(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    default_backend: DefaultBackend | None = None


class Storage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    checkpoints: Checkpoints | None = Field(
        None,
        description="LangGraph run-state checkpointer. The one block that does NOT inherit storage.runtime: postgres here needs `pip install 'swarmkit-runtime[postgres]'`, so it is opt-in rather than implied.",
    )
    audit: Audit | None = Field(
        None,
        description="Append-only audit trail. Inherits storage.runtime unless it overrides it.",
    )
    artifacts: Artifacts | None = Field(
        None,
        description="Where pipeline stage outputs live. Defaults to `database` on the storage.runtime engine. Read by the runtime since the bundled orchestrator shipped, but undeclarable until 1.130.0 — `additionalProperties: false` rejected the very key the code looked for.",
    )
    runtime: Runtime | None = Field(
        None,
        description="Backend for jobs, conversations, usage, pipeline sagas, artifacts, fleet enrollment and governed memory. Every other storage block inherits this one unless it overrides it. Defaults to sqlite at .swarmkit/store.sqlite.",
    )
    knowledge_bases: KnowledgeBases | None = None


class CompressionBackend(Enum):
    """
    Compression backend. off (default): no compression. columnar: built-in lossless JSON minify + array-of-uniform-dicts rewrite to {columns, rows}. headtail: reversible-lossy — keep head+tail, elide the middle, recallable via the context_retrieve tool (for lossy-tolerant surfaces like logs). plugin: a custom ContextCompressor named by backend_class.
    """

    off = "off"
    columnar = "columnar"
    headtail = "headtail"
    plugin = "plugin"


class CompressionOverride1(BaseModel):
    """
    A per-surface compression rule. At least one of match / match_server is required.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    match: str = Field(
        ...,
        description="Glob matched against the tool/skill name (e.g. 'get-logs', 'frigate*').",
        min_length=1,
    )
    match_server: str | None = Field(
        None,
        description="Glob matched against the MCP server id backing the tool (e.g. 'frigate', 'logs-*').",
        min_length=1,
    )
    backend: CompressionBackend | None = "off"
    backend_class: str | None = Field(
        None,
        description="Fully-qualified Python class path of a custom ContextCompressor (used when backend=plugin), e.g. 'my_pkg.compressors.LearnedCompressor'.",
    )
    min_bytes: int | None = Field(
        2000,
        description="Payloads smaller than this (in characters) are left untouched — avoids overhead on small results.",
        ge=0,
    )


class CompressionOverride2(BaseModel):
    """
    A per-surface compression rule. At least one of match / match_server is required.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    match: str | None = Field(
        None,
        description="Glob matched against the tool/skill name (e.g. 'get-logs', 'frigate*').",
        min_length=1,
    )
    match_server: str = Field(
        ...,
        description="Glob matched against the MCP server id backing the tool (e.g. 'frigate', 'logs-*').",
        min_length=1,
    )
    backend: CompressionBackend | None = "off"
    backend_class: str | None = Field(
        None,
        description="Fully-qualified Python class path of a custom ContextCompressor (used when backend=plugin), e.g. 'my_pkg.compressors.LearnedCompressor'.",
    )
    min_bytes: int | None = Field(
        2000,
        description="Payloads smaller than this (in characters) are left untouched — avoids overhead on small results.",
        ge=0,
    )


class Planning(BaseModel):
    """
    Default planning behavior for all topologies in this workspace. Topology-level planning overrides these defaults.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    scope_required: bool | None = Field(
        False, description="Leaders must call create-scope before synthesis."
    )
    two_phase: bool | None = Field(
        False, description="Enforce two-phase planning for all topologies."
    )
    synthesis_roles: list[str] | None = Field(
        None,
        description="Default synthesis/output roles for all topologies: auto-wired to depend on research tasks so they run last. Defaults to ['self', 'document-writer']. Topology-level planning overrides this.",
    )
    synthesizer_role: str | None = Field(
        None,
        description="Default role name for the automatic synthesis step. Defaults to 'synthesizer'. Topology-level planning overrides this.",
    )


class Synthesis(BaseModel):
    """
    Automatic synthesis config. When set, the compiler invokes a large-context model directly with all research results instead of having the architect write the document.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    provider: str = Field(
        ..., description="Model provider ID (e.g. google, openrouter, anthropic)."
    )
    model: str = Field(
        ..., description="Model name for synthesis (e.g. gemini-2.5-flash)."
    )
    prompt: str | None = Field(
        None,
        description="Custom system prompt for the synthesizer. Overrides the platform default. Use this to control document style, diagram generation (mermaid), grounding rules, and section handling.",
    )


class Trigger(StrEnum):
    """
    When the skill fires: pre_input (before agent runs, validates user input), post_output (after agent output), checkpoint (between task batches), pre_synthesis (before final synthesis).
    """

    pre_input = "pre_input"
    post_output = "post_output"
    checkpoint = "checkpoint"
    pre_synthesis = "pre_synthesis"


class DecisionSkillBinding(BaseModel):
    """
    Binds a decision skill to a trigger point. Workspace bindings are inherited by all topologies; topology bindings can override by id.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(
        ...,
        description="Decision skill ID. Must exist in workspace skill registry.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    trigger: Trigger = Field(
        ...,
        description="When the skill fires: pre_input (before agent runs, validates user input), post_output (after agent output), checkpoint (between task batches), pre_synthesis (before final synthesis).",
    )
    scope: str | None = Field(
        None,
        description="Comma-separated agent IDs this binding applies to. Default '*' = all agents in the topology.",
    )
    required: bool | None = Field(
        True,
        description="Whether a failing verdict from this skill STOPS the run. true (the default) means a `fail` rejects the output; false means the skill still runs and its rejection is advisory — logged, not fatal. It does NOT disable the binding: use `enabled: false` for that. Until 1.169.0 a falsey `required` silently discarded the binding, so an advisory skill was never evaluated at all.",
    )
    config: dict[str, Any] | None = Field(
        None,
        description="Skill-specific configuration (confidence thresholds, retry limits, etc).",
    )
    enabled: bool | None = Field(
        True,
        description="Whether this binding is active. Set false in a topology to switch off a binding inherited from the workspace. Separate from `required` because the two are different questions — whether a skill runs, and whether its verdict can stop the run.",
    )


class Jobs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    max_concurrent: int | None = Field(
        5, description="Maximum number of concurrent topology executions.", ge=1
    )
    timeout_seconds: int | None = Field(
        300, description="Per-job execution timeout in seconds.", ge=1
    )


class Mcp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    enabled: bool | None = Field(
        True, description="Whether to start MCP servers at boot in serve mode."
    )


class Provider2(Enum):
    """
    none: open access (default; only safe on loopback). api_key: bearer tokens from a static key registry. jwt: OIDC-compliant JWT bearer tokens (RS256/ES256 + JWKS).
    """

    none = "none"
    api_key = "api_key"
    jwt = "jwt"


class Tier(Enum):
    """
    Transport scope tier: read (observe) | run (+ execute) | admin (+ mutate artifacts/rollout). Expands to serve:* scopes.
    """

    read = "read"
    run = "run"
    admin = "admin"


class ServerAuthKey(BaseModel):
    """
    One API key. Grant scopes via a tier (read/run/admin → serve:* scopes) OR explicit scopes — not both.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    key_ref: str = Field(
        ...,
        description="Reference to the secret, never a literal: 'env:VAR' or a credentials entry. Resolved at startup.",
    )
    client_id: str = Field(
        ..., description="Stable id for this caller (appears in audit).", min_length=1
    )
    client_name: str | None = Field(
        None, description="Human-readable name. Defaults to client_id."
    )
    tier: Tier | None = Field(
        None,
        description="Transport scope tier: read (observe) | run (+ execute) | admin (+ mutate artifacts/rollout). Expands to serve:* scopes.",
    )
    scopes: list[str] | None = Field(
        None,
        description="Explicit scopes, as an alternative to tier (e.g. ['serve:read','serve:run']).",
    )


class PromoteCriteria(BaseModel):
    """
    Conditions that must ALL be met for auto-promotion of a canary version.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    min_runs: int | None = Field(
        None,
        description="Minimum number of completed runs before promotion is eligible.",
        ge=1,
    )
    error_rate_below: float | None = Field(
        None,
        description="Maximum error rate (failed/total). E.g. 0.05 = 5% error rate threshold.",
        ge=0.0,
        le=1.0,
    )
    drift_below: float | None = Field(
        None,
        description="Maximum average drift score. E.g. 0.30 = low drift tolerance.",
        ge=0.0,
        le=2.0,
    )
    window_minutes: int | None = Field(
        60,
        description="Evaluation window in minutes. Only runs within this window count toward promotion criteria.",
        ge=1,
    )


class Effects1(Enum):
    """
    Whether this command changes anything. Not inferrable from the binary — `curl` POSTs and `jq` takes `-i` — so the pack author declares it. Undeclared means `write`, so an unclassified command fails closed. `permission: readonly` denies every `write` command.
    """

    read = "read"
    write = "write"


class Parse(Enum):
    text = "text"
    json = "json"
    lines = "lines"


class Output(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    parse: Parse | None = "text"


class CommandSpec(BaseModel):
    """
    A single command in a pack. `argv` is executed directly — there is no shell, so a substituted value can never become an argument or an operator.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    description: str | None = None
    argv: list[str] = Field(
        ...,
        description="argv, executed with no shell. `{name}` placeholders are filled from the skill's declared inputs and are always passed as exactly one argument, never re-parsed. `{credential.*}` is rejected here — secrets reach a command through the pack's `env` only, so they cannot be model-placed, cannot appear in an audit line, and cannot be read from `ps`.",
        min_length=1,
    )
    effects: Effects1 | None = Field(
        "write",
        description="Whether this command changes anything. Not inferrable from the binary — `curl` POSTs and `jq` takes `-i` — so the pack author declares it. Undeclared means `write`, so an unclassified command fails closed. `permission: readonly` denies every `write` command.",
    )
    output: Output | None = None


class BinaryRequirement(BaseModel):
    """
    A binary this pack needs, checked at workspace load rather than at run time. A topology that only runs where a binary happens to exist is less portable data than one that does not, and the failure should name the binary rather than surface as an exec error mid-run.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    binary: str = Field(..., min_length=1)
    version: str | None = Field(
        None,
        description="Constraint such as '>=1.7', compared against the binary's --version output. An unparseable version is a load error, not a silent pass.",
    )


class Permission1(Enum):
    """
    Governance permission tier for this pack's commands, matching mcp_server. open: skip governance checks. cautious (default): reads auto-approved, writes go through governance. strict: all calls require explicit approval. readonly: every command declaring `effects: write` is denied.
    """

    open = "open"
    cautious = "cautious"
    strict = "strict"
    readonly = "readonly"


class CommandPack(BaseModel):
    """
    A named set of local commands exposed to skills through `implementation.type: command`. Governed exactly as an mcp_server is — the pack carries the permission tier, the skill carries `iam.required_scopes`.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    description: str | None = None
    commands: list[CommandSpec] = Field(..., min_length=1)
    requires: list[BinaryRequirement] | None = None
    permission: Permission1 | None = Field(
        "cautious",
        description="Governance permission tier for this pack's commands, matching mcp_server. open: skip governance checks. cautious (default): reads auto-approved, writes go through governance. strict: all calls require explicit approval. readonly: every command declaring `effects: write` is denied.",
    )
    permission_overrides: dict[str, PermissionOverrides] | None = Field(
        None, description="Per-command tier overrides. Keys are command ids."
    )
    timeout_seconds: int | None = Field(
        30,
        description="Pack default. A command with no ceiling can take a run down with it, so an omitted value means the built-in default, never unbounded.",
        ge=1,
    )
    timeout_overrides: dict[str, int] | None = Field(
        None,
        description="Per-command timeout overrides in seconds. Keys are command ids.",
    )
    max_output_bytes: int | None = Field(
        10485760,
        description="Combined stdout+stderr ceiling. Exceeding it fails the call rather than truncating, since a truncated result read as complete is the worse outcome.",
        ge=1,
    )
    cwd: str | None = Field(
        None,
        description="Working directory. Supports ${VAR} expansion. Defaults to workspace root.",
    )
    env: dict[str, str] | None = Field(
        None,
        description="Environment for every command in the pack. Supports ${VAR} expansion and `{credential.<ref>}` resolved against `credentials_ref`. This is the only place a secret may reach a command.",
    )
    credentials_ref: str | None = None


class Governance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    provider: Provider = Field(
        ..., description="GovernanceProvider implementation (design §8.5)."
    )
    policy_language: PolicyLanguage | None = Field(
        None, description="§21 open question — default yaml for v1.0."
    )
    config: dict[str, Any] | None = None
    limits: Limits | None = Field(
        None,
        description="Circuit breaker thresholds. Prevents runaway execution and cost overruns.",
    )
    decision_skills: list[DecisionSkillBinding] | None = Field(
        None,
        description="Mandatory decision skills that fire at specified trigger points. Topologies inherit these and can override by id.",
    )


class ContextCompression(BaseModel):
    """
    Opt-in read-side compression of bulk tool/MCP output before it re-enters an agent's context. Off by default. Never applied to the audit log or the inter-agent contract. Env vars SWARMKIT_CONTEXT_COMPRESSION and SWARMKIT_CONTEXT_COMPRESSION_MIN_BYTES override the default per deployment. See design/details/context-compression.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    backend: CompressionBackend | None = "off"
    backend_class: str | None = Field(
        None,
        description="Fully-qualified Python class path of a custom ContextCompressor (used when backend=plugin), e.g. 'my_pkg.compressors.LearnedCompressor'.",
    )
    min_bytes: int | None = Field(
        2000,
        description="Payloads smaller than this (in characters) are left untouched — avoids overhead on small results.",
        ge=0,
    )
    overrides: list[CompressionOverride1 | CompressionOverride2] | None = Field(
        None,
        description="Per-surface rules matched by tool-name and/or server-id glob. The first override that matches wins; otherwise the top-level backend/min_bytes apply.",
    )


class ServerAuthConfig(BaseModel):
    """
    Provider-specific auth config. keys[] for api_key; issuer/audience/jwks_url/scopes_claim/client_id/scope for jwt; identity/identity_name for none.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    keys: list[ServerAuthKey] | None = Field(
        None, description="API key registry (provider: api_key)."
    )
    issuer: str | None = Field(None, description="OIDC issuer URL (provider: jwt).")
    audience: str | None = Field(
        None, description="Expected token audience (provider: jwt). Default: swarmkit."
    )
    jwks_url: str | None = Field(
        None,
        description="JWKS URL (provider: jwt). Defaults to {issuer}/.well-known/jwks.json.",
    )
    scopes_claim: str | None = Field(
        None, description="JWT claim holding scopes (provider: jwt). Default: scope."
    )
    client_id: str | None = Field(
        None,
        description="The browser's OIDC client registration (provider: jwt), advertised to clients via /auth-info. The server never uses it to validate anything — it advertises it because the portal ships as a pre-built static export, so a build-time env var would be fixed at publish and the same wheel serves every deployment. Without it the portal cannot start a sign-in flow.",
    )
    scope: str | None = Field(
        None,
        description="OIDC scopes the portal requests (provider: jwt), advertised via /auth-info. Default: openid profile email.",
    )
    identity: str | None = Field(
        None,
        description="Who the caller is asserted to be (provider: none). Default: anonymous. This mode already grants wildcard scopes and authorizes everything, so naming the operator confers no new capability — but the approval engine matches this value against members: in swarm/roles.yaml, so it is what makes a local gate approvable without standing up an identity provider. Asserted, not authenticated: the audit records provider=none.",
    )
    identity_name: str | None = Field(
        None,
        description="Display name for that identity (provider: none). Defaults to the identity itself.",
    )


class CanaryVersion(BaseModel):
    """
    A single version in a canary route with its traffic weight and optional promotion criteria.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    version: str = Field(
        ...,
        description="Topology version (semver). Must match a topology file's metadata.version.",
        pattern="^\\d+\\.\\d+\\.\\d+$",
    )
    weight: int = Field(
        ...,
        description="Percentage of traffic routed to this version (0-100).",
        ge=0,
        le=100,
    )
    promote_when: PromoteCriteria | None = Field(
        None,
        description="Auto-promotion criteria. When all conditions are met, this version is promoted to 100% traffic.",
    )


class ServerAuth(BaseModel):
    """
    HTTP authentication for swarmkit serve. Off by default (provider: none). For a non-loopback bind, leaving provider=none refuses to start unless require_on_nonloopback is false (default-secure). See design/details/control-plane/12-auth.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    provider: Provider2 | None = Field(
        "none",
        description="none: open access (default; only safe on loopback). api_key: bearer tokens from a static key registry. jwt: OIDC-compliant JWT bearer tokens (RS256/ES256 + JWKS).",
    )
    require_on_nonloopback: bool | None = Field(
        True,
        description="When true (default), a non-loopback bind (--host other than 127.0.0.1/::1) with provider=none refuses to start. Set false to allow an open non-loopback bind (not recommended).",
    )
    config: ServerAuthConfig | None = None


class CanaryRoute(BaseModel):
    """
    Traffic splitting rule for a single topology.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    topology: str = Field(
        ...,
        description="Topology name (matches metadata.name). Must exist in the workspace.",
    )
    versions: list[CanaryVersion] = Field(
        ..., description="Version entries. Weights must sum to 100.", min_length=2
    )


class Canary(BaseModel):
    """
    Canary deployment configuration. Routes traffic between topology versions by weight with optional auto-promotion. See design/details/canary-deployments.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    routes: list[CanaryRoute] | None = Field(
        None,
        description="Canary routes. Each route splits traffic for one topology across multiple versions.",
    )


class ServerConfig(BaseModel):
    """
    Configuration for swarmkit serve mode. Controls job concurrency, timeouts, MCP server lifecycle, and canary deployments.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    jobs: Jobs | None = None
    mcp: Mcp | None = None
    canary: Canary | None = Field(
        None,
        description="Canary deployment configuration. Routes traffic between topology versions by weight with optional auto-promotion. See design/details/canary-deployments.md.",
    )
    auth: ServerAuth | None = None


class SwarmKitWorkspace(BaseModel):
    """
    Deployment-level config: identity, governance, model providers, MCP registry, storage. See design §9.3 and design/details/workspace-schema-v1.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    apiVersion: Literal["swarmkit/v1"]
    kind: Literal["Workspace"]
    metadata: Metadata
    organisation: OrgOrTeam | None = None
    team: OrgOrTeam | None = None
    governance: Governance | None = None
    identity: Identity | None = None
    model_providers: list[ModelProviderRegistration] | None = None
    credentials: dict[str, CredentialRef] | None = None
    mcp_servers: list[McpServer] | None = None
    command_packs: list[CommandPack] | None = Field(
        None,
        description="Local command packs — the sibling of `mcp_servers` for capabilities that already exist as binaries and would otherwise need a wrapper server written for them.",
    )
    storage: Storage | None = None
    context_compression: ContextCompression | None = None
    planning: Planning | None = None
    synthesis: Synthesis | None = None
    server: ServerConfig | None = None
