# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  workspace.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    name: str = Field(..., min_length=1)
    description: str | None = None
    annotations: dict[str, str] | None = Field(
        None,
        description="Arbitrary key-value metadata the runtime ignores. For enterprise use: cost_center, team, environment, compliance tags, etc.",
    )


class OrgOrTeam(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    name: str | None = None


class Provider(Enum):
    """
    GovernanceProvider implementation (design §8.5).
    """

    agt = "agt"
    mock = "mock"
    custom = "custom"


class PolicyLanguage(Enum):
    """
    §21 open question — default yaml for v1.0.
    """

    yaml = "yaml"
    rego = "rego"
    cedar = "cedar"


class Limits(BaseModel):
    """
    Circuit breaker thresholds. Prevents runaway execution and cost overruns.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    max_steps_per_agent: int | None = Field(
        None,
        description="Maximum execution steps per individual agent before abort.",
        ge=1,
    )
    max_steps_per_run: int | None = Field(
        None,
        description="Maximum total steps across all agents in a single run. Default: 500.",
        ge=1,
    )
    max_cost_per_run_usd: float | None = Field(
        None,
        description="Maximum estimated LLM cost (USD) per run before abort.",
        ge=0.0,
    )


class Provider1(Enum):
    """
    Human-identity provider (design §16.1).
    """

    builtin = "builtin"
    auth0 = "auth0"
    okta = "okta"
    google = "google"
    azure_ad = "azure-ad"
    oidc = "oidc"


class Identity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    provider: Provider1 = Field(
        ..., description="Human-identity provider (design §16.1)."
    )
    config: dict[str, Any] | None = None


class ModelProviderRegistration(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    class_: str = Field(
        ..., alias="class", description="Fully-qualified Python class path."
    )
    provider_id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    config: dict[str, Any] | None = None


class Source(Enum):
    env = "env"
    file = "file"
    hashicorp_vault = "hashicorp-vault"
    aws_secrets_manager = "aws-secrets-manager"
    gcp_secret_manager = "gcp-secret-manager"
    azure_key_vault = "azure-key-vault"
    plugin = "plugin"


class CredentialRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    source: Source
    provider_id: str | None = Field(
        None,
        description="Required when source=plugin. Names the registered SecretsProvider.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    config: dict[str, Any] = Field(
        ...,
        description="Provider-specific configuration. Runtime validates shape per source.",
    )


class Transport(Enum):
    stdio = "stdio"
    http = "http"


class Permission(Enum):
    """
    Governance permission tier for this server's tools. open: skip governance checks. cautious (default): reads auto-approved, writes go through governance. strict: all calls require explicit approval. readonly: write operations denied.
    """

    open = "open"
    cautious = "cautious"
    strict = "strict"
    readonly = "readonly"


class PermissionOverrides(Enum):
    open = "open"
    cautious = "cautious"
    strict = "strict"
    readonly = "readonly"


class McpServer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    transport: Transport
    command: list[str] | None = Field(
        None, description="Required when transport=stdio."
    )
    endpoint: str | None = Field(None, description="Required when transport=http.")
    env: dict[str, str] | None = Field(
        None,
        description="Environment variables passed to a stdio server. Values support ${VAR} expansion from the runtime process environment. Use `credentials_ref` for secrets; `env` is for configuration.",
    )
    cwd: str | None = Field(
        None,
        description="Working directory for stdio servers. Supports ${VAR} expansion. Defaults to workspace root.",
    )
    credentials_ref: str | None = None
    sandboxed: bool | None = Field(
        None, description="True forces Docker-or-equivalent isolation (design §8.8)."
    )
    sandbox_image: str | None = Field(
        None,
        description="Docker image for sandboxed servers. Defaults to swarmkit-mcp-sandbox (Python + mcp SDK). Use node:22-slim for Node.js servers.",
    )
    permission: Permission | None = Field(
        "cautious",
        description="Governance permission tier for this server's tools. open: skip governance checks. cautious (default): reads auto-approved, writes go through governance. strict: all calls require explicit approval. readonly: write operations denied.",
    )
    permission_overrides: dict[str, PermissionOverrides] | None = Field(
        None,
        description="Per-tool permission overrides. Keys are MCP tool names, values are permission tiers that override the server default.",
    )


class Backend(Enum):
    sqlite = "sqlite"
    postgres = "postgres"


class Checkpoints(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    backend: Backend | None = None
    path: str | None = None
    url: str | None = None


class Backend1(Enum):
    agt = "agt"
    sqlite = "sqlite"
    postgres = "postgres"


class Audit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    backend: Backend1 | None = None
    retention_days: int | None = Field(None, ge=1)
    url: str | None = None


class Backend2(Enum):
    """
    Storage backend. sqlite (default, zero config) or postgres (production, shared).
    """

    sqlite = "sqlite"
    postgres = "postgres"


class Runtime(BaseModel):
    """
    Backend for jobs, conversations, and usage tracking. Defaults to sqlite at .swarmkit/store.sqlite.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    backend: Backend2 | None = Field(
        "sqlite",
        description="Storage backend. sqlite (default, zero config) or postgres (production, shared).",
    )
    url: str | None = Field(
        None,
        description="Connection URL for postgres backend. Supports ${ENV_VAR} interpolation. Ignored for sqlite.",
    )


class DefaultBackend(Enum):
    sqlite = "sqlite"
    postgres = "postgres"


class KnowledgeBases(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    default_backend: DefaultBackend | None = None


class Storage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    checkpoints: Checkpoints | None = None
    audit: Audit | None = None
    runtime: Runtime | None = Field(
        None,
        description="Backend for jobs, conversations, and usage tracking. Defaults to sqlite at .swarmkit/store.sqlite.",
    )
    knowledge_bases: KnowledgeBases | None = None


class Backend3(Enum):
    """
    Compression backend. off (default): no compression. columnar: built-in lossless JSON minify + array-of-uniform-dicts rewrite to {columns, rows}.
    """

    off = "off"
    columnar = "columnar"


class ContextCompression(BaseModel):
    """
    Opt-in read-side compression of bulk tool/MCP output before it re-enters an agent's context. Off by default. Never applied to the audit log or the inter-agent contract. Env vars SWARMKIT_CONTEXT_COMPRESSION and SWARMKIT_CONTEXT_COMPRESSION_MIN_BYTES override these values per deployment. See design/details/context-compression.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    backend: Backend3 | None = Field(
        "off",
        description="Compression backend. off (default): no compression. columnar: built-in lossless JSON minify + array-of-uniform-dicts rewrite to {columns, rows}.",
    )
    min_bytes: int | None = Field(
        2000,
        description="Payloads smaller than this (in characters) are left untouched — avoids columnar overhead on small results.",
        ge=0,
    )


class Planning(BaseModel):
    """
    Default planning behavior for all topologies in this workspace. Topology-level planning overrides these defaults.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    scope_required: bool | None = Field(
        False, description="Leaders must call create-scope before synthesis."
    )
    two_phase: bool | None = Field(
        False, description="Enforce two-phase planning for all topologies."
    )


class Synthesis(BaseModel):
    """
    Automatic synthesis config. When set, the compiler invokes a large-context model directly with all research results instead of having the architect write the document.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    provider: str = Field(
        ..., description="Model provider ID (e.g. google, openrouter, anthropic)."
    )
    model: str = Field(
        ..., description="Model name for synthesis (e.g. gemini-2.5-flash)."
    )
    prompt: str | None = Field(
        None,
        description="Custom system prompt for the synthesizer. Overrides the platform default. Use this to control document style, diagram generation (mermaid), grounding rules, and section handling.",
    )


class Trigger(Enum):
    """
    When the skill fires: pre_input (before agent runs, validates user input), post_output (after agent output), checkpoint (between task batches), pre_synthesis (before final synthesis).
    """

    pre_input = "pre_input"
    post_output = "post_output"
    checkpoint = "checkpoint"
    pre_synthesis = "pre_synthesis"


class DecisionSkillBinding(BaseModel):
    """
    Binds a decision skill to a trigger point. Workspace bindings are inherited by all topologies; topology bindings can override by id.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(
        ...,
        description="Decision skill ID. Must exist in workspace skill registry.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    trigger: Trigger = Field(
        ...,
        description="When the skill fires: pre_input (before agent runs, validates user input), post_output (after agent output), checkpoint (between task batches), pre_synthesis (before final synthesis).",
    )
    scope: str | None = Field(
        None,
        description="Comma-separated agent IDs this binding applies to. Default '*' = all agents in the topology.",
    )
    required: bool | None = Field(
        True,
        description="If true, output is rejected when this skill returns a failing verdict. Set false to disable an inherited workspace binding.",
    )
    config: dict[str, Any] | None = Field(
        None,
        description="Skill-specific configuration (confidence thresholds, retry limits, etc).",
    )


class Jobs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    max_concurrent: int | None = Field(
        5, description="Maximum number of concurrent topology executions.", ge=1
    )
    timeout_seconds: int | None = Field(
        300, description="Per-job execution timeout in seconds.", ge=1
    )


class Mcp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    enabled: bool | None = Field(
        True, description="Whether to start MCP servers at boot in serve mode."
    )


class PromoteCriteria(BaseModel):
    """
    Conditions that must ALL be met for auto-promotion of a canary version.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    min_runs: int | None = Field(
        None,
        description="Minimum number of completed runs before promotion is eligible.",
        ge=1,
    )
    error_rate_below: float | None = Field(
        None,
        description="Maximum error rate (failed/total). E.g. 0.05 = 5% error rate threshold.",
        ge=0.0,
        le=1.0,
    )
    drift_below: float | None = Field(
        None,
        description="Maximum average drift score. E.g. 0.30 = low drift tolerance.",
        ge=0.0,
        le=2.0,
    )
    window_minutes: int | None = Field(
        60,
        description="Evaluation window in minutes. Only runs within this window count toward promotion criteria.",
        ge=1,
    )


class Governance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    provider: Provider = Field(
        ..., description="GovernanceProvider implementation (design §8.5)."
    )
    policy_language: PolicyLanguage | None = Field(
        None, description="§21 open question — default yaml for v1.0."
    )
    config: dict[str, Any] | None = None
    limits: Limits | None = Field(
        None,
        description="Circuit breaker thresholds. Prevents runaway execution and cost overruns.",
    )
    decision_skills: list[DecisionSkillBinding] | None = Field(
        None,
        description="Mandatory decision skills that fire at specified trigger points. Topologies inherit these and can override by id.",
    )


class CanaryVersion(BaseModel):
    """
    A single version in a canary route with its traffic weight and optional promotion criteria.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    version: str = Field(
        ...,
        description="Topology version (semver). Must match a topology file's metadata.version.",
        pattern="^\\d+\\.\\d+\\.\\d+$",
    )
    weight: int = Field(
        ...,
        description="Percentage of traffic routed to this version (0-100).",
        ge=0,
        le=100,
    )
    promote_when: PromoteCriteria | None = Field(
        None,
        description="Auto-promotion criteria. When all conditions are met, this version is promoted to 100% traffic.",
    )


class CanaryRoute(BaseModel):
    """
    Traffic splitting rule for a single topology.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    topology: str = Field(
        ...,
        description="Topology name (matches metadata.name). Must exist in the workspace.",
    )
    versions: list[CanaryVersion] = Field(
        ..., description="Version entries. Weights must sum to 100.", min_length=2
    )


class Canary(BaseModel):
    """
    Canary deployment configuration. Routes traffic between topology versions by weight with optional auto-promotion. See design/details/canary-deployments.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    routes: list[CanaryRoute] | None = Field(
        None,
        description="Canary routes. Each route splits traffic for one topology across multiple versions.",
    )


class ServerConfig(BaseModel):
    """
    Configuration for swarmkit serve mode. Controls job concurrency, timeouts, MCP server lifecycle, and canary deployments.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    jobs: Jobs | None = None
    mcp: Mcp | None = None
    canary: Canary | None = Field(
        None,
        description="Canary deployment configuration. Routes traffic between topology versions by weight with optional auto-promotion. See design/details/canary-deployments.md.",
    )


class SwarmKitWorkspace(BaseModel):
    """
    Deployment-level config: identity, governance, model providers, MCP registry, storage. See design §9.3 and design/details/workspace-schema-v1.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    apiVersion: Literal["swarmkit/v1"]
    kind: Literal["Workspace"]
    metadata: Metadata
    organisation: OrgOrTeam | None = None
    team: OrgOrTeam | None = None
    governance: Governance | None = None
    identity: Identity | None = None
    model_providers: list[ModelProviderRegistration] | None = None
    credentials: dict[str, CredentialRef] | None = None
    mcp_servers: list[McpServer] | None = None
    storage: Storage | None = None
    context_compression: ContextCompression | None = None
    planning: Planning | None = None
    synthesis: Synthesis | None = None
    server: ServerConfig | None = None
