"""Generate ``llms-full.txt`` — the expanded, single-file LLM corpus.

``llms.txt`` (repo root) is the compact, link-first map. ``llms-full.txt`` is its
companion from the llmstxt.org convention: the *full text* of the core docs inlined
into one file so an LLM can ingest the whole corpus in a single fetch, no link
following. This script concatenates a curated, ordered manifest — the ``llms.txt``
map, then the building-swarms playbook, all 11 artifact references, the operate
references, and the core design notes — into that file.

Two identical copies are written, same discipline as the bundled schema copies:

- ``llms-full.txt``            — repo root, tool-discoverable.
- ``docs/site/llms-full.txt``  — the copy MkDocs publishes at
  ``https://delivstat.github.io/swarmkit/llms-full.txt``.

The output is generated, not hand-edited. Regenerate whenever ``llms.txt`` or any
manifest doc changes:

    python scripts/build_llms_full.py        # write the files
    python scripts/build_llms_full.py --check # fail if the committed files are stale

``test_llms_full_txt.py`` runs the ``--check`` path so CI catches drift.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_SITE = REPO_ROOT / "docs" / "site"
SITE_URL = "https://delivstat.github.io/swarmkit"

ROOT_OUTPUT = REPO_ROOT / "llms-full.txt"
PUBLISHED_OUTPUT = DOCS_SITE / "llms-full.txt"

# Ordered manifest, grouped into parts. Each entry is a repo-root-relative path.
# `llms.txt` is inlined first as the map; the rest are the docs whose full text an
# LLM needs to build swarms without following a single link.
MANIFEST: list[tuple[str, list[str]]] = [
    (
        "The map (llms.txt)",
        ["llms.txt"],
    ),
    (
        "The playbook",
        ["docs/site/guides/building-swarms.md"],
    ),
    (
        # Configuration whose failure mode is silence: a curated fact that reaches no agent, a
        # binding accepted and never evaluated. An LLM asked "why is memory not working" needs
        # this, and neither answer is derivable from the schemas alone.
        "Memory and decision-skill bindings",
        ["docs/site/guides/memory-and-decision-skills.md"],
    ),
    (
        "Artifact references",
        [
            "docs/site/reference/topology.md",
            "docs/site/reference/workspace.md",
            "docs/site/reference/archetypes.md",
            "docs/site/reference/skills.md",
            "docs/site/reference/funnel.md",
            "docs/site/reference/contract.md",
            "docs/site/reference/role-registry.md",
            "docs/site/reference/trigger.md",
            "docs/site/reference/executor-adapter.md",
            "docs/site/reference/approval-policy.md",
        ],
    ),
    (
        "Operate references",
        [
            "docs/site/reference/cli.md",
            "docs/site/reference/serve.md",
            "docs/site/reference/orchestrator-integration.md",
            "docs/site/reference/governed-memory.md",
        ],
    ),
    (
        "Design notes (the depth)",
        [
            "docs/site/design-notes/gate-funnel.md",
            "docs/site/design-notes/gate-state-and-deferring-approval.md",
            "docs/site/design-notes/extracting-the-pipeline.md",
            "docs/site/design-notes/skill-prerequisites.md",
            "docs/site/design-notes/funnel-verification-check.md",
            "docs/site/design-notes/multi-party-approval.md",
            "docs/site/design-notes/contract-registry.md",
            "docs/site/design-notes/executor-abstraction.md",
            "docs/site/design-notes/structured-output-governance.md",
            "docs/site/design-notes/governance-provider-interface.md",
            "docs/site/design-notes/model-provider-abstraction.md",
            "docs/site/design-notes/dag-dependency-graph.md",
        ],
    ),
]

_RULE = "═" * 78


def _published_url(rel_path: str) -> str:
    """The GitHub Pages URL a docs/site file is served at (dir-style, no .md)."""
    if rel_path == "llms.txt":
        return f"{SITE_URL}/llms.txt"
    if rel_path.startswith("docs/site/"):
        slug = rel_path[len("docs/site/") :].removesuffix(".md")
        return f"{SITE_URL}/{slug}/"
    return f"{SITE_URL}/{rel_path}"


def build() -> str:
    """Assemble the full corpus as one string (the file content)."""
    parts: list[str] = []

    parts.append("# SwarmKit — llms-full.txt")
    parts.append("")
    parts.append(
        "> The expanded, single-file corpus: the full text of the playbook, all 11 "
        "artifact\n> references, and the core design notes inlined so an LLM can ingest "
        "everything in one\n> fetch — no link following. For the compact, link-first map, "
        f"see llms.txt ({SITE_URL}/llms.txt).\n>\n> GENERATED by scripts/build_llms_full.py "
        "from the source docs — do not edit by hand;\n> regenerate with "
        "`python scripts/build_llms_full.py`."
    )
    parts.append("")

    # Contents
    parts.append("## Contents")
    parts.append("")
    for part_no, (section_title, rel_paths) in enumerate(MANIFEST, start=1):
        parts.append(f"{part_no}. **{section_title}**")
        for rel_path in rel_paths:
            title = _doc_title(REPO_ROOT / rel_path, rel_path)
            parts.append(f"   - {title} — `{rel_path}`")
    parts.append("")

    # Body
    for part_no, (section_title, rel_paths) in enumerate(MANIFEST, start=1):
        parts.append(_RULE)
        parts.append(f"# Part {part_no} — {section_title}")
        parts.append(_RULE)
        parts.append("")
        for rel_path in rel_paths:
            abs_path = REPO_ROOT / rel_path
            content = abs_path.read_text(encoding="utf-8").strip("\n")
            parts.append(_RULE)
            parts.append(f"## Source: {rel_path}")
            parts.append(f"## Published: {_published_url(rel_path)}")
            parts.append(_RULE)
            parts.append("")
            parts.append(content)
            parts.append("")

    return "\n".join(parts).rstrip("\n") + "\n"


def _doc_title(abs_path: Path, rel_path: str) -> str:
    """The first markdown H1 of a doc, else its filename."""
    try:
        for line in abs_path.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    except OSError:
        pass
    return Path(rel_path).name


def _write(content: str) -> None:
    ROOT_OUTPUT.write_text(content, encoding="utf-8")
    PUBLISHED_OUTPUT.write_text(content, encoding="utf-8")


def main(argv: list[str]) -> int:
    content = build()
    if "--check" in argv:
        stale = [
            p
            for p in (ROOT_OUTPUT, PUBLISHED_OUTPUT)
            if not p.is_file() or p.read_text(encoding="utf-8") != content
        ]
        if stale:
            names = ", ".join(str(p.relative_to(REPO_ROOT)) for p in stale)
            print(
                f"llms-full.txt is stale: {names}\nRegenerate: python scripts/build_llms_full.py",
                file=sys.stderr,
            )
            return 1
        print("llms-full.txt is up to date.")
        return 0
    _write(content)
    print(
        f"Wrote {ROOT_OUTPUT.relative_to(REPO_ROOT)} and "
        f"{PUBLISHED_OUTPUT.relative_to(REPO_ROOT)} "
        f"({len(content):,} bytes)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
