#!/usr/bin/env python
"""Generate the control-plane UI's ``KNOWN_VERBS`` from the panel's canonical ``VERB_TIERS``.

The verb→tier map is the cross-package API contract: the runtime connector enforces it
(``swarmkit_runtime.connect.VERB_ROUTES``), the panel mirrors it (``_verbs.VERB_TIERS``, pinned to
the runtime by ``test_verb_contract``), and the fleet UI gates the command dropdown on it. This
makes the UI's copy **generated** from the panel instead of hand-maintained, so it can't silently
drift — it already had (the hand-written list was missing ``deploy``). Run via ``just
codegen-verbs``; CI fails on any uncommitted diff. The recipe runs ``biome format`` after this so
the emitted file is byte-stable against the linter.
"""

from __future__ import annotations

from pathlib import Path

from swarmkit_control_plane._verbs import VERB_TIERS

OUT = Path(__file__).resolve().parent.parent / "packages/control-plane-ui/lib/generated/verbs.ts"

_HEADER = (
    "// @generated by scripts/codegen_verbs.py from swarmkit_control_plane._verbs.VERB_TIERS.\n"
    "// Do not edit by hand — run `just codegen-verbs` and commit the result.\n"
)


def render() -> str:
    """Render the TypeScript module (tab-indented; ``biome format`` normalises the rest)."""
    entries = "".join(
        f'\t{{ verb: "{verb}", tier: "{tier}" }},\n' for verb, tier in VERB_TIERS.items()
    )
    return (
        f"{_HEADER}\n"
        'export type Tier = "read" | "run" | "admin";\n\n'
        "export interface KnownVerb {\n"
        "\tverb: string;\n"
        "\ttier: Tier;\n"
        "}\n\n"
        f"export const KNOWN_VERBS: readonly KnownVerb[] = [\n{entries}] as const;\n"
    )


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT} ({len(VERB_TIERS)} verbs)")


if __name__ == "__main__":
    main()
