# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  archetype.schema.json

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Role(Enum):
    """
    Must match the agent role where this archetype is instantiated.
    """

    root = "root"
    leader = "leader"
    worker = "worker"


class Identifier(RootModel[str]):
    root: str = Field(..., pattern="^[a-z][a-z0-9-]*$")


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    name: str = Field(..., min_length=1)
    description: str = Field(..., min_length=10)


class Model(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    provider: str | None = None
    name: str | None = None
    temperature: float | None = Field(None, ge=0.0, le=2.0)
    max_tokens: int | None = Field(None, ge=1)


class Prompt(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    system: str | None = None
    persona: str | None = None


class Category(Enum):
    capability = "capability"
    decision = "decision"
    coordination = "coordination"
    persistence = "persistence"


class Abstract(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    category: Category
    capability: str | None = Field(
        None, description="Free-text tag matched by the topology resolver."
    )


class SkillEntry1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    abstract: Abstract


class Iam(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    base_scope: list[str] | None = None
    elevated_scopes: list[str] | None = None


class AuthoredBy(Enum):
    human = "human"
    authored_by_swarm = "authored_by_swarm"
    derived_from_template = "derived_from_template"
    imported_from_registry = "imported_from_registry"
    vendor_published = "vendor_published"


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    authored_by: AuthoredBy
    authored_date: date | None = None
    version: str = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    registry: str | None = None
    vendor: str | None = None


class Defaults(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    model: Model | None = None
    prompt: Prompt | None = None
    skills: list[Identifier | SkillEntry1] | None = None
    iam: Iam | None = None


class SwarmKitArchetype(BaseModel):
    """
    A kind of agent (noun). See design §6.6, §13 and design/details/archetype-schema-v1.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    apiVersion: Literal["swael/v1"]
    kind: Literal["Archetype"]
    metadata: Metadata
    role: Role = Field(
        ...,
        description="Must match the agent role where this archetype is instantiated.",
    )
    defaults: Defaults
    provenance: Provenance
