# ruff: noqa
# mypy: ignore-errors
# This file is generated from the canonical JSON Schema. Do not edit by hand.
# Regenerate with: just schema-codegen
# generated by datamodel-codegen:
#   filename:  trigger.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Type(Enum):
    """
    Discriminator; per-type config shape validated at runtime.
    """

    cron = "cron"
    webhook = "webhook"
    file_watch = "file_watch"
    manual = "manual"
    plugin = "plugin"


class Identifier(RootModel[str]):
    root: str = Field(..., pattern="^[a-z][a-z0-9-]*$")


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    id: str = Field(..., pattern="^[a-z][a-z0-9-]*$")
    name: str = Field(..., min_length=1)
    description: str | None = None


class Method(Enum):
    hmac = "hmac"
    bearer = "bearer"
    api_key = "api_key"


class WebhookAuth(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    method: Method
    credentials_ref: str = Field(
        ..., description="Name of a workspace `credentials` entry holding the secret."
    )
    header: str | None = Field(
        None,
        description="HTTP header carrying the auth material (method-dependent default).",
    )


class Config(BaseModel):
    """
    Type-specific configuration. Runtime validates shape per type.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    auth: WebhookAuth | None = Field(
        None, description="Only meaningful for type=webhook."
    )


class SwarmKitTrigger(BaseModel):
    """
    Workspace-level schedule / webhook / file-watch / manual / plugin trigger. Unifies schedules and triggers under one kind. See design §5.4 and design/details/trigger-schema-v1.md.
    """

    model_config = ConfigDict(
        extra="forbid",
        populate_by_name=True,
    )
    apiVersion: Literal["swael/v1"]
    kind: Literal["Trigger"]
    metadata: Metadata
    type: Type = Field(
        ..., description="Discriminator; per-type config shape validated at runtime."
    )
    enabled: bool | None = Field(
        None, description="Default true. Disabled triggers load but do not fire."
    )
    targets: list[Identifier] = Field(
        ...,
        description="Topology IDs this trigger fires. Fired in parallel.",
        min_length=1,
    )
    provider_id: str | None = Field(
        None,
        description="Required when type=plugin. Names a registered TriggerProvider.",
        pattern="^[a-z][a-z0-9-]*$",
    )
    config: Config | None = Field(
        None,
        description="Type-specific configuration. Runtime validates shape per type.",
    )
